import json
import re
from anthropic import Anthropic

"""
Chat assistant for laymen asking open-ended questions in plain language.

This is the wiring layer that connects a user's free-text question to the
retrieval infrastructure already built this session -- semantic_retrieval.py
(real embeddings, scored, with conflict detection) and retrieval.py (exact
lookup for judgment doctrines). It does NOT introduce any new way of
deciding legal correctness: every answer either quotes real retrieved text
directly, or is generated by Claude with strict instructions to use ONLY
that retrieved text -- never to answer from general knowledge, never to
invent a section number or holding.

Flow, and why each step exists:
  1. Scope classification (cheap Haiku call) -- decides whether a question
     is plausibly about BNS/BNSS arrest/FIR procedure at all, BEFORE
     spending an embedding call on it. Confirmed necessity: a layman will
     ask genuinely anything ("how do I sue my neighbour", "is this legal",
     small talk) and semantic search always returns SOMETHING, even for
     completely unrelated questions -- classification catches the "this
     isn't even the right kind of question" case before retrieval ever
     runs, rather than relying on the similarity threshold alone to catch
     every kind of irrelevance.
  2. Semantic retrieval (only for in-scope questions) -- real embeddings,
     real similarity scores, real conflict detection (see
     semantic_retrieval.py's docstring for the confirmed "rioting" case
     this specifically guards against).
  3. Response generation -- Claude reads ONLY the retrieved real text and
     is instructed never to go beyond it. This keeps the same
     deterministic-grounding guarantee the rest of this project relies on:
     the LLM explains and phrases, it does not decide or invent.
     CONFIRMED (2026-09-01) the instruction alone is not a hard
     guarantee -- a real, low-frequency (~1/10 trials) case slipped
     through where the model named a real BNSS section it was never
     actually given for that query. generate_grounded_response() now
     deterministically checks its own output against retrieved_text
     (see _find_ungrounded_sections) and retries once before ever
     showing an unverified claim -- the LLM proposes, Python verifies.

Every response also carries a plain-language "what to do next" pointer,
per the explicit design goal that this tool should act as a guide/advisor
for a layman, not just answer-and-stop.
"""

import json
from anthropic import Anthropic

try:
    from main import client as _main_client
except ImportError:
    _main_client = None

try:
    import streamlit as st
    _api_key = st.secrets.get("ANTHROPIC_API_KEY")
except Exception:
    _api_key = None

if _main_client is not None:
    client = _main_client
elif _api_key:
    client = Anthropic(api_key=_api_key)
else:
    client = None
    


HAIKU_MODEL = "claude-haiku-4-5-20251001"
SONNET_MODEL = "claude-sonnet-5"  # per this environment's current model list


SCOPE_CLASSIFIER_PROMPT = """You are a scope classifier for a legal tool that helps with Indian criminal procedure. This chat feature specifically covers BNS/BNSS arrest, FIR, and police procedure topics, grounded in Arnesh Kumar, D.K. Basu, Vihaan Kumar, Satender Kumar Antil, Youth Bar Association, Prabir Purkayastha, Pankaj Bansal, NALSA, and applying High Court judgments.

The WIDER tool (outside this chat feature, via document upload) ALSO has working, real compliance-check logic for two other domains: bank account freezing (BNS Sections 106/107) and cheque bounce notices (Section 138, Negotiable Instruments Act). This chat feature's own search corpus does not yet include those domains' case law, but the tool as a whole genuinely handles them -- a question about them should be redirected to the document-upload feature, NOT told "this isn't covered" or "consult a lawyer", since that would be inaccurate.

CRITICAL: this chat feature does NOT cover every Indian criminal law. A question can genuinely be about "arrest" or "cognizable/non-cognizable" and still be out of this CHAT feature's scope, if the specific offence involved is governed by a law neither this chat feature nor the wider tool covers (e.g. POCSO, UAPA, NDPS, dowry-specific acts, company/tax law offences). Do NOT classify a question as in_scope just because it uses words like "arrest", "cognizable", "police", or "FIR" -- check whether the SPECIFIC OFFENCE NAMED (if any) is actually a BNS/BNSS offence, a bank-freeze/cheque-bounce matter (see below), or a procedural question with no specific other-law offence attached.

Classify the user's question into exactly one category:

"in_scope" -- plausibly about arrest, FIR, police procedure, bail, or a criminal offence's classification (cognizable/non-cognizable) under BNS/BNSS specifically, where the offence involved (if named) is genuinely a BNS/BNSS offence, or the question is purely about general arrest PROCEDURE with no other-law offence named. Includes vague or layman-phrased questions about "being arrested", "police took my X", "is this a crime", specific BNS offence names (theft, cheating, assault, rioting, etc.), FIR copies, notice before arrest, etc.

"covered_elsewhere_in_tool" -- specifically about bank account freezing (BNS 106/107) or cheque bounce (Section 138 NI Act), including arrest threats or police involvement in either. This wider tool has real, working compliance logic for these via document upload, even though this chat feature's own search corpus does not yet include their case law.

"adjacent_uncovered" -- genuinely about Indian law, but NOT about BNS/BNSS criminal procedure, bank freezing, or cheque bounce. Examples: POCSO, UAPA, NDPS, dowry-specific acts, civil suits, property disputes, family law/divorce, employment law, consumer complaints, contract disputes, tax law, company law offences.

"unrelated" -- not a legal question at all, small talk, or about something with no connection to Indian law (e.g. "what's the weather", "who are you", general chit-chat).

If (and only if) the category is "covered_elsewhere_in_tool", also decide which specific domain: "freeze" (bank account freezing) or "cheque_bounce" (Section 138 NI Act cheque dishonour). For every other category, redirect_domain must be null.

Respond with ONLY a JSON object, no other text:
{{"category": "in_scope" | "covered_elsewhere_in_tool" | "adjacent_uncovered" | "unrelated", "redirect_domain": "freeze" | "cheque_bounce" | null, "reasoning": "one short sentence"}}

User's question: {question}"""

def _extract_text_from_response(response):
    """Shared helper: safely extracts text content from an Anthropic
    API response, regardless of block order or the presence of
    non-text blocks (e.g. ThinkingBlock).
 
    FIXED 2026-08-29: every call site in this project previously did
    `response.content[0].text`, assuming the first content block is
    always plain text. CONFIRMED REAL FAILURE (in layman_summary.py,
    same bug class, same session): 'ThinkingBlock' object has no
    attribute 'text' -- for a sufficiently complex prompt, the model
    can return a ThinkingBlock as the first content item, followed by
    the actual TextBlock.

    CORRECTION (2026-09-01): this docstring already claimed the helper
    was "applied here defensively to both call sites in this file" --
    that was FALSE. All three real call sites in this file
    (classify_scope, and both the original + retry calls in
    generate_grounded_response) still did raw `.content[0].text.strip()`
    right below this very function, never actually calling it. CONFIRMED
    REAL FAILURE, found via live user testing: exactly this crash
    ('ThinkingBlock' object has no attribute 'text') fired inside
    generate_grounded_response's try/except, was silently swallowed,
    and returned None -- which the caller correctly falls back on, but
    the actual cause (a client bug, not "generation genuinely failed")
    was invisible. Now actually wired into all three call sites."""
    text_block = next((block for block in response.content if hasattr(block, "text")), None)
    if text_block is None:
        raise ValueError("No text block found in response.content -- only non-text blocks returned.")
    return text_block.text


def classify_scope(question):
    """Returns ('in_scope' | 'covered_elsewhere_in_tool' | 'adjacent_uncovered' | 'unrelated',
    reasoning, redirect_domain) or (None, None, None) if the classifier call itself fails --
    callers must treat None as an honest 'could not determine', not assume in_scope or
    unrelated by default, since guessing either way here risks either
    wasting a retrieval call on something clearly out of scope, or
    wrongly turning away a genuinely answerable question.

    redirect_domain: ADDED 2026-09-01, only meaningful when category is
    'covered_elsewhere_in_tool' -- 'freeze' or 'cheque_bounce', naming
    which of the two dedicated free-text interview flows
    (freeze_interview_flow.py / cheque_bounce_interview_flow.py) the
    question actually belongs to, so the app can hand the user's
    already-typed question straight to the RIGHT flow with one click
    instead of a generic 'go upload a document' dead end. None for
    every other category, and None (not a guess) if the model omits it
    or returns something unrecognised for a covered_elsewhere_in_tool
    response -- the app must be able to fall back to a domain-less
    redirect rather than launching the wrong interview flow."""
    if client is None:
        return None, None, None
    try:
        # Haiku, not Sonnet: this is a bounded 4-way routing classification
        # against an explicit rubric (the module docstring's step 1 always
        # described it as "cheap Haiku call" -- the code had drifted to
        # Sonnet). It does NOT decide any legal question -- misrouting only
        # picks the wrong canned redirect / answer path, and a parse failure
        # still falls back to the honest (None, None, None) "could not
        # determine". The answer itself and its deterministic grounding
        # checks stay on Sonnet (generate_grounded_response).
        response = client.messages.create(
            model=HAIKU_MODEL,
            max_tokens=1500,
            messages=[{"role": "user", "content": SCOPE_CLASSIFIER_PROMPT.format(question=question)}],
        )
        raw = _extract_text_from_response(response).strip()
        # Defensive: strip markdown code fences if the model adds them
        # despite the "ONLY a JSON object" instruction.
        if raw.startswith("```"):
            raw = raw.strip("`")
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()
        parsed = json.loads(raw)
        category = parsed.get("category")
        if category not in ("in_scope", "covered_elsewhere_in_tool", "adjacent_uncovered", "unrelated"):
            return None, None, None
        redirect_domain = parsed.get("redirect_domain")
        if category != "covered_elsewhere_in_tool" or redirect_domain not in ("freeze", "cheque_bounce"):
            redirect_domain = None
        return category, parsed.get("reasoning", ""), redirect_domain
    except Exception:
        return None, None, None

# ---------------------------------------------------------------------------
# RESPONSE_GENERATION_PROMPT -- design notes / failure history.
#
# Every rule below is load-bearing; each traces to a real observed
# failure. The war-story detail lives here (as a comment, never sent to
# the model) so the prompt itself stays short -- a ~1100-word prompt
# stuffed with inline "CONFIRMED REAL FAILURE" digressions was itself
# degrading answers (2026-09-01 eval: answers ran 500-800 words, cited
# up to 17 sections, buried the actionable step).
#
#  - No "Indian Penal Code" / "IPC": a past answer called BNS 318
#    "Section 318 of the Indian Penal Code (BNS)". The IPC is the OLD law
#    BNS replaced; this corpus never mentions it.
#  - No "retrieved text" / "the information below": a layperson under
#    stress must never see the machinery.
#  - No compliance verdict: the chat feature EXPLAINS; the deterministic
#    engine (document upload / guided interviews) DECIDES. Hard line.
#  - Subsection precision: an answer described 318(4)'s punishment
#    without ever naming it "318(4)".
#  - Don't hedge after answering: given Section 109(1)'s two punishment
#    conditions -- both stated correctly -- an answer THEN added a false
#    "a real exception exists that couldn't be extracted" caveat.
#  - Lead with the practical, cap the section list, keep it short
#    (2026-09-01 eval): the old "MANDATORY name and describe EVERY
#    retrieved section" rule (added to stop judgments crowding out
#    statute) overcorrected into laundry lists behind a "these don't
#    seem to fit" hedge. Replaced with: prioritise, cap at 4, omit the
#    rest entirely; offence section before procedure sections keeps the
#    original intent.
#  - One currency clause, not a paragraph (2026-09-01 eval): answers
#    surfaced citation_currency NOT_YET_VERIFIED notes as hand-wringing
#    "treat this judgment with caution" paragraphs -- internal metadata
#    language, not for a layperson.
#  - "Right now" block for situations: a competitor tool's answer to the
#    goat-theft query led with concrete custody actions ("ask for the
#    FIR number, don't sign blank papers") and read far better for
#    someone actually in that moment; ours led with statutory exposition.
# ---------------------------------------------------------------------------
RESPONSE_GENERATION_PROMPT = """You are a warm, careful guide helping a layperson understand Indian criminal law and procedure (BNS / BNSS). You are NOT a lawyer and do NOT give legal advice -- you explain what the law and the courts say, in plain words, and point to one concrete next step.

## Hard rules (never break)
- Use ONLY the legal information given below. Never add a section number, case holding, punishment, or the NAME of any act/law from your own knowledge -- even if you are sure it is right.
- Never write "the Indian Penal Code" or "IPC" unless those exact words appear below. Refer only to the act named below (BNS or BNSS).
- Never reveal the machinery: no "the retrieved text", "the information I have", "the material below", "the classification table". State the law directly ("Section 303 covers..."); if something genuinely isn't covered, say "I don't have information on...".
- Never give a compliance verdict about the person's own situation ("your arrest was illegal", "this was lawful"). Explain what the law requires and what would matter; whether it was followed needs facts you don't have.
- When you name a section that has subsections in the material below, always include the exact subsection ("Section 318(4)", not "Section 318").
- If you have already stated a condition clearly ("the punishment is X, or Y if Z"), do NOT then add a vaguer caveat implying the detail is incomplete. Only flag a gap when you are genuinely missing a specific fact you cannot state.

## What to include, what to leave out
- The material below is roughly in order of relevance. Pick the 2-4 provisions (plus any one case) that actually answer the question and build the answer around those.
- Cite AT MOST 4 distinct section numbers. If a retrieved section only tangentially relates, OMIT IT ENTIRELY -- do not describe it and do not explain why it doesn't apply.
- Address the section(s) defining the OFFENCE the person asks about before general arrest-procedure sections -- the offence is usually the most direct answer.
- If a provision or case below carries a note about its legal currency, fold it in as ONE short plain clause ("...though the exact scope of this is under review by a larger bench"). Never write a separate paragraph about verification status or "treat this with caution".

## Shape and length
- If the question describes something that HAS ALREADY HAPPENED to the person or someone close to them (an arrest, a search, an FIR, a frozen account), open with a short **"Right now"** part: 2-3 concrete things they can do or ask for immediately. Then the relevant law. Then what key facts are still unclear. Then the closing line.
- If it is a general question ("what is Section X", "what are my rights if..."), skip "Right now" -- just explain clearly in short labelled parts.
- Keep the whole answer under about 300 words (400 only for a genuinely multi-part question). Someone may be reading this in a police station -- brevity helps them.
- Warm, plain tone; explain any legal term you must use.
- End with exactly ONE "what you can do next" line (e.g. "if you have the FIR or arrest memo, you can upload it here for a full check", or "the 'describe my situation' option above will take you through this step by step"). Never repeat it.
{conflict_instruction}

The person's question:
{question}

The legal information relevant to it (statute text and court judgments) -- present this as your own direct knowledge of the law:
{retrieved_text}

Write the answer now, following the shape and length rules above."""


_CONFLICT_INSTRUCTION = """- IMPORTANT: the sections below genuinely DISAGREE with each other on a key point (e.g. some are arrestable without a warrant, others are not). Do NOT blend them into one narrative paragraph. Structure your answer as clearly separated scenarios, each labeled with its exact section number, e.g.:
  "**If [scenario 1, naming the exact section]:** [what applies]"
  "**If [scenario 2, naming the exact section]:** [what applies]"
  Make the fork in the law visually obvious, not something the reader has to infer from careful reading."""
  
  
# ---------------------------------------------------------------------
# REPLACE generate_grounded_response with this version -- adds an
# optional `model` parameter, defaulting to HAIKU_MODEL so every
# existing call site (answer_question, which never passes `model`)
# behaves EXACTLY as before. Only a test script that explicitly passes
# model=SONNET_MODEL will use the stronger model. This is deliberately
# non-invasive: no production behavior changes until you decide to
# change answer_question's calls, which this does NOT do.
# ---

_SECTION_REFERENCE_PATTERN = re.compile(r"\bSection\s+(\d+)", re.IGNORECASE)


def _extract_section_numbers(text: str) -> set:
    """Returns the set of base section numbers (e.g. '274' from 'Section
    274(2)') referenced anywhere in text. Base number only -- subsection
    suffixes are stripped since retrieved_text's own labels are also
    base-number-only (see get_statute_section's docstring)."""
    return {m.group(1) for m in _SECTION_REFERENCE_PATTERN.finditer(text or "")}


def _find_ungrounded_sections(response_text: str, retrieved_text: str) -> list:
    """CONFIRMED REAL BUG (2026-09-01), found via live user testing: asked
    'police came to my house and arrested me directly saying that i stole
    a goat', the model's answer confidently named 'Section 274 of the
    BNSS' (summons-case procedure) with an accurate description of its
    real text -- but Section 274 never appeared anywhere in retrieved_text
    for that query. Reproduced the exact same question+retrieved_text
    pair 9 more times: 0/9 repeated the hallucination, confirming this is
    a real but LOW-FREQUENCY, STOCHASTIC failure of the "use ONLY the
    information provided" instruction in RESPONSE_GENERATION_PROMPT, not
    a deterministic bug -- explicitly ruled out citation_currency.py's
    prompt injection as the cause (identical hallucination rate with and
    without it, across the same trials). The section named was REAL and
    accurately described (confirmed via retrieval.get_statute_section)
    -- this is the model drawing on its own training knowledge of actual
    Indian law, not inventing fiction, which makes it MORE dangerous to
    silently trust, not less: a fabricated-sounding claim is easier to
    doubt than a lucid, textually-perfect, but ungrounded-for-THIS-query
    one. Since no prompt wording can be proven to eliminate a stochastic
    LLM failure, this is a deterministic Python safety net instead --
    the same discipline as the rest of this project: verify the claim
    against real source text before it reaches the user, never trust
    confidence alone. A false positive here (a real section mentioned in
    retrieved_text but phrased differently, e.g. digits embedded in a
    citation like '(2000) 2 SCC 380') is possible but rare and safe --
    it only triggers one retry, not a hard failure.

    Returns the sorted list of section numbers response_text references
    that do not appear anywhere (as a plain substring) in retrieved_text.
    Empty list means nothing to worry about -- the common case."""
    referenced = _extract_section_numbers(response_text)
    if not referenced:
        return []
    return sorted(num for num in referenced if num not in retrieved_text)


_UNGROUNDED_RETRY_INSTRUCTION = """
IMPORTANT CORRECTION: your previous answer to this exact question referenced Section(s) {sections}, but none of those section numbers appear anywhere in the information provided above. Do not mention Section(s) {sections} at all in your new answer, even if you are confident they are real and relevant -- only use section numbers that literally appear in the information above. Write a new, complete answer from scratch, following all the same rules."""


_MISMATCH_RETRY_INSTRUCTION = """
IMPORTANT CORRECTION: your previous answer to this exact question stated the wrong cognizable/bailable status for one or more sections. {details} These are fixed facts from the statute's own official classification table, not a matter of interpretation. Write a new, complete answer from scratch, stating each of these correctly, following all the same rules."""


_SECTION_WITH_SUBSECTION_PAT = re.compile(r"\bSection\s+(\d{1,3})(?:\((\d+[a-z]?)\))?", re.IGNORECASE)


def _gather_offence_variants(matches) -> dict:
    """Merges every match's 'all_variants' field (subsection key ->
    BNS_SECTION_DATA entry) into one dict, across however many matches
    were fed into this prompt. Judgment matches and BNSS-procedure
    matches contribute nothing (they carry no all_variants) -- what's
    left is exactly the deterministic cognizable/bailable ground truth
    that format_retrieved_text_for_prompt already showed the model, so
    the verification below can never disagree with what the model was
    actually given (no separate, potentially-drifted lookup)."""
    merged = {}
    for m in matches or []:
        merged.update(m.get("all_variants") or {})
    return merged


def _claimed_status(window: str, negative_words, positive_word) -> "bool | None":
    """What does this stretch of the model's own answer claim -- True,
    False, or nothing stated? negative_words (e.g. 'non-cognizable') are
    checked FIRST since the positive word is always a literal substring
    of the negative one ('cognizable' inside 'non-cognizable')."""
    low = window.lower()
    if any(w in low for w in negative_words):
        return False
    if positive_word in low:
        return True
    return None


def _find_cognizable_bailable_mismatches(response_text: str, variants: dict) -> list:
    """CONFIRMED GAP (2026-09-01, Phase 2 of the chat-quality plan): the
    grounding check above verifies a cited 'Section N' appears somewhere
    in retrieved_text -- it never checks whether the model's CLAIM about
    that section (cognizable? bailable?) matches the deterministic
    BNS_SECTION_DATA fact that was actually fed to it. That table is the
    SAME one the compliance engine uses; find_relevant_sections() already
    computes it for every statute match. This closes the gap with the
    identical discipline the grounding check established: Python
    verifies, the LLM only phrases -- never trust a checkable legal fact
    to model prose alone.

    variants: sec_key ('318' or '318(4)') -> BNS_SECTION_DATA entry, from
    _gather_offence_variants() over the SAME matches fed to the prompt.

    Deliberately conservative to avoid false positives on genuinely
    multi-condition sections -- e.g. 303(2): the general case is
    cognizable/non-bailable, but the under-Rs.5,000-first-offence carve-
    out is non-cognizable/bailable, and BOTH are real, correct answers
    for 'Section 303(2)' depending on which condition the model is
    describing at that point in the answer, which this function cannot
    determine from a keyword window alone. A claim is flagged ONLY when
    it matches NEITHER of the section's known valid values for that
    field -- a genuine contradiction, not just a different condition
    than the top-level default. This means multi-condition sections are
    effectively unchecked (both values are 'valid'); the check still has
    real teeth on the majority of BNS sections, which are single-
    condition.

    A bare 'Section 303' mention (no subsection) is only checked when
    every subsection variant of that bare number agrees on the field in
    question -- otherwise which one the model means is genuinely
    ambiguous from the number alone, and this stays silent rather than
    guessing.

    Returns a list of {'section', 'field', 'claimed', 'valid'} dicts.
    Empty list is the common, reassuring case -- and the immediate
    return when variants is empty means this is a pure no-op for
    judgment-only answers or matches with no BNS_SECTION_DATA entry."""
    if not variants:
        return []

    problems = []
    section_hits = list(_SECTION_WITH_SUBSECTION_PAT.finditer(response_text))
    for i, m in enumerate(section_hits):
        num, sub = m.group(1), m.group(2)
        key = f"{num}({sub})" if sub else num
        data = variants.get(key)
        if data is None and not sub:
            bare_family = [v for k, v in variants.items() if k == num or k.startswith(f"{num}(")]
            if len(bare_family) == 1:
                data = bare_family[0]
        if data is None:
            continue

        window_end = section_hits[i + 1].start() if i + 1 < len(section_hits) else len(response_text)
        window = response_text[m.end(): min(window_end, m.end() + 300)]

        valid_cognizable = {data.get("cognizable")}
        valid_bailable = {data.get("bailable")}
        if data.get("has_multiple_conditions"):
            for cond in data.get("all_conditions", []):
                valid_cognizable.add(cond.get("cognizable"))
                valid_bailable.add(cond.get("bailable"))

        claimed_cog = _claimed_status(window, ["non-cognizable", "not cognizable"], "cognizable")
        if claimed_cog is not None and claimed_cog not in valid_cognizable:
            problems.append({"section": key, "field": "cognizable", "claimed": claimed_cog,
                             "valid": sorted((v for v in valid_cognizable if v is not None), reverse=True)})

        claimed_bail = _claimed_status(window, ["non-bailable", "not bailable"], "bailable")
        if claimed_bail is not None and claimed_bail not in valid_bailable:
            problems.append({"section": key, "field": "bailable", "claimed": claimed_bail,
                             "valid": sorted((v for v in valid_bailable if v is not None), reverse=True)})

    return problems


def _looks_like_situation(response_text: str) -> bool:
    """PHASE 3 (2026-09-01, chat-quality plan): True when the answer
    opens with the '**Right now**' block RESPONSE_GENERATION_PROMPT
    instructs the model to lead with for a question describing something
    that ALREADY HAPPENED to the person or someone close to them (an
    arrest, a search, an FIR, a frozen account) -- see the prompt's
    'Shape and length' section.

    Deliberately reuses this already-generated signal instead of a
    second classifier call: zero extra API cost or latency, and it is
    already reliable in practice -- across the Phase 1/2 eval set, every
    situation-shaped answer opened with this heading and no general-
    question answer did (e.g. 'what is section 318', 'what are my
    rights if arrested' correctly do NOT trigger it; 'the police took me
    without telling me why' correctly does).

    Used by app.py to decide whether to additionally offer a one-click
    handoff into the real arrest interview (interview_flow.py) below an
    otherwise-unchanged chat answer -- unlike the freeze/cheque handoff,
    which REPLACES the chat answer (chat has no case-law corpus for
    those domains at all), this is ADDITIVE: the chat corpus for arrest/
    FIR/police-procedure is good post-Phase-1/2, so the explanation
    stays, and the handoff is offered as a faster path to a real verdict
    for someone who's already living the situation, not a replacement."""
    if not response_text:
        return False
    return "right now" in response_text.lstrip()[:50].lower()


def _format_mismatch(problem: dict) -> str:
    """'Section 318(4) is cognizable, not non-cognizable as you wrote.'"""
    field = problem["field"]
    def word(v):
        return field if v else f"non-{field}"
    correct = " or ".join(word(v) for v in problem["valid"])
    return f"Section {problem['section']} is {correct}, not {word(problem['claimed'])} as you wrote."


def generate_grounded_response(question, retrieved_text, is_conflict=False, model=SONNET_MODEL, matches=None):
    """Generates a plain-language answer using ONLY the given retrieved
    text. Returns None if the generation call fails -- callers should
    fall back to showing the raw retrieved text directly rather than
    inventing a summary.
 
    is_conflict: set True when called for a 'conflicting_matches' result,
    so the prompt explicitly instructs the model to structure its answer
    as separated scenarios rather than blending disagreeing provisions
    into one narrative -- confirmed real failure: a genuine
    conflicting_matches case (cheating: 318(1) non-arrestable vs 318(4)
    arrestable) was answered as a single fluent paragraph that only
    named one subsection explicitly, hiding the fork in the law the
    conflicting_matches state exists specifically to surface.
 
    model: ADDED 2026-08-28 for a deliberate, evidence-gated Haiku-vs-
    Sonnet comparison. CORRECTION (2026-09-01): this docstring previously
    claimed the default was HAIKU_MODEL "so this parameter is 100%
    backward compatible" -- that was already false when written: line 64
    has HAIKU_MODEL commented out entirely, and the actual default
    parameter value above is SONNET_MODEL. Every call site (answer_question
    never passes model) has been running on Sonnet, not Haiku. Corrected
    here rather than left stale.

    GROUNDING VERIFICATION (added 2026-09-01): after generating a
    response, checks every "Section N" it names against retrieved_text
    via _find_ungrounded_sections() -- see that function's docstring for
    the confirmed real hallucination this guards against (a real,
    accurately-described BNSS section, but one that was never actually
    retrieved for the query at hand).

    COGNIZABLE/BAILABLE VERIFICATION (added 2026-09-01, Phase 2 of the
    chat-quality plan): separately, checks every claim the response makes
    about a BNS offence section's cognizable/bailable status against the
    real BNS_SECTION_DATA facts in `matches` (via
    _find_cognizable_bailable_mismatches() -- see its docstring). The
    grounding check alone only proves a section NUMBER was really
    retrieved; it says nothing about whether the model's CLAIM about that
    section is correct. This closes that gap with the same discipline:
    the classification table is the deterministic source of truth, the
    model only phrases it.

    matches: the list of enriched match dicts fed into retrieved_text
    (each may carry 'all_variants', the BNS_SECTION_DATA ground truth for
    that section). Optional and defaults to None so every existing call
    site that doesn't pass it (and every test that calls this with only
    2 positional args) behaves exactly as before -- with no matches, the
    mismatch check is a guaranteed no-op.

    Either problem triggers ONE combined retry with an explicit
    correction. If the retry still has either problem, returns None --
    the same "give up honestly" signal already used for a failed API
    call, so callers fall back to showing the raw retrieved text rather
    than ever displaying a claim that could not be verified."""
    if client is None:
        return None
    try:
        conflict_instruction = _CONFLICT_INSTRUCTION if is_conflict else ""
        prompt = RESPONSE_GENERATION_PROMPT.format(
            question=question, retrieved_text=retrieved_text,
            conflict_instruction=conflict_instruction,
        )
        response = client.messages.create(
            model=model,
            # Headroom only -- the prompt targets 300-400 words. 1500 was
            # truncating long answers mid-sentence and silently dropping
            # the closing "what you can do next" line (2026-09-01 eval).
            max_tokens=2000,
            messages=[{"role": "user", "content": prompt}],
        )
        response_text = _extract_text_from_response(response).strip()

        variants = _gather_offence_variants(matches)
        ungrounded = _find_ungrounded_sections(response_text, retrieved_text)
        mismatches = _find_cognizable_bailable_mismatches(response_text, variants)

        if ungrounded or mismatches:
            retry_prompt = prompt
            if ungrounded:
                retry_prompt += _UNGROUNDED_RETRY_INSTRUCTION.format(sections=", ".join(ungrounded))
            if mismatches:
                retry_prompt += _MISMATCH_RETRY_INSTRUCTION.format(
                    details=" ".join(_format_mismatch(p) for p in mismatches)
                )
            retry_response = client.messages.create(
                model=model,
                max_tokens=2000,
                messages=[{"role": "user", "content": retry_prompt}],
            )
            retry_text = _extract_text_from_response(retry_response).strip()
            if (_find_ungrounded_sections(retry_text, retrieved_text)
                    or _find_cognizable_bailable_mismatches(retry_text, variants)):
                return None
            return retry_text

        return response_text
    except Exception:
        return None


# "section 318", "sec 318", "s.318", "318 of BNS", "BNS 318", "BNSS 35(3)"
_EXPLICIT_SECTION_PAT = re.compile(
    r"\b(?:section|sec\.?|s\.?)\s*(\d{1,3})(?:\s*\(\d+[a-z]?\))?\s*(?:of\s+the\s+|of\s+|,\s*)?(bnss|bns)?\b"
    r"|\b(bnss|bns)\s*(?:section\s*)?(\d{1,3})(?:\s*\(\d+[a-z]?\))?\b",
    re.IGNORECASE,
)


def _explicit_section_matches(question: str, max_sections: int = 2) -> list:
    """If the question literally names one or more section numbers, return
    a match dict per section with that section's real statute text pulled
    directly via retrieval.get_statute_section -- shaped like a
    statute_doctrine_map override so it flows through the same downstream
    handling.

    Act resolution: if the question says "BNS" or "BNSS" next to the
    number, trust that. Otherwise default to BNS -- a bare section number
    almost always means a substantive offence, and BNS has only 358
    sections, so a famous old IPC number like 420 (cheating) or 302
    (murder) simply doesn't resolve and yields nothing rather than
    pulling an unrelated BNSS procedural section of the same number.
    Someone genuinely asking about a BNSS procedure section by number is
    rare and will be caught by normal semantic retrieval anyway."""
    from retrieval import get_statute_section

    found = []  # list of (num_str, act_hint_or_None), in question order, deduped
    seen = set()
    for m in _EXPLICIT_SECTION_PAT.finditer(question or ""):
        num = m.group(1) or m.group(4)
        act_hint = (m.group(2) or m.group(3) or "").upper() or None
        if not num or num in seen:
            continue
        seen.add(num)
        found.append((num, act_hint))
        if len(found) >= max_sections:
            break

    results = []
    for num, act_hint in found:
        act = act_hint if act_hint in ("BNS", "BNSS") else "BNS"
        if act == "BNS":
            # _bns_section_as_match already pulls the real text and adds
            # the BNS_SECTION_DATA cognizable/bailable/max_years
            # enrichment (PHASE 2, 2026-09-01) -- shared with
            # _offence_keyword_matches so the two paths can't drift.
            match = _bns_section_as_match(num)
            if match:
                results.append(match)
            continue
        data = get_statute_section(act, num)
        if data:
            # BNSS procedural sections carry no First-Schedule
            # cognizable/bailable classification, so no all_variants here.
            results.append({
                "act": data["act"],
                "section_number": data["section_number"],
                "text": data["text"],
                "source": "explicit_section_ref",
            })
    return results


# CONFIRMED REAL FAILURE (2026-09-01, live): "police... arrested me...
# saying that i stole a goat" -- Section 303 (theft) scored only ~0.362
# on the embeddings, BEHIND Section 274 (summons-case procedure, ~0.376)
# and tied with several noise matches. The answer sometimes mentioned
# 274. For a small set of offences a layperson describes in one plain
# word ("stole", "cheated"), the right BNS section is not a guess -- so
# anchor it deterministically, exactly like an explicitly-typed section
# number, rather than hoping the embedding ranks it first. Checked in
# order, first hit wins (so "attempt to murder" resolves before
# "murder"). Kept deliberately short and high-precision -- only words
# that map to ONE offence unambiguously when someone is describing an
# accusation against them.
_OFFENCE_KEYWORD_ANCHORS = [
    (re.compile(r"\b(attempt(ed|ing)?\s+to\s+murder|tried\s+to\s+kill)\b", re.I), "109"),
    (re.compile(r"\b(murder(ed|ing)?|killed\s+(him|her|someone|a\s+(man|woman|person)))\b", re.I), "103"),
    (re.compile(r"\b(sto(le|len)|steal(ing)?|theft|thief|shoplift\w*)\b", re.I), "303"),
    (re.compile(r"\b(cheat(ed|ing)?|defraud\w*)\b", re.I), "318"),
    (re.compile(r"\b(extort\w*|blackmail\w*)\b", re.I), "308"),
    (re.compile(r"\b(robbery|robbed|mugg\w*)\b", re.I), "309"),
    (re.compile(r"\b(criminal\s+breach\s+of\s+trust|misappropriat\w*|embezzl\w*)\b", re.I), "316"),
    (re.compile(r"\b(kidnap\w*|abduct\w*)\b", re.I), "137"),
    (re.compile(r"\b(rape|raped|raping)\b", re.I), "64"),
    (re.compile(r"\b(forg(ed|ery|ing)|fake\s+(document|signature|cheque))\b", re.I), "336"),
    (re.compile(r"\b(defam\w*)\b", re.I), "356"),
    (re.compile(r"\b(criminal\s+intimidation|threaten\w*\s+to\s+(kill|hurt|harm))\b", re.I), "351"),
]


def _bns_section_as_match(num: str) -> "dict | None":
    """Build a prompt-ready match dict for a BNS section number: its real
    statute text plus the BNS_SECTION_DATA cognizable/bailable
    enrichment. Shared by _explicit_section_matches (typed section
    numbers) and _offence_keyword_matches (offence words). None if the
    section doesn't resolve."""
    from retrieval import get_statute_section

    data = get_statute_section("BNS", num)
    if not data:
        return None
    return {
        "act": data["act"],
        "section_number": data["section_number"],
        "text": data["text"],
        "source": "explicit_section_ref",
        "all_variants": _bns_section_variants(data["section_number"]),
    }


def _offence_keyword_matches(question: str) -> list:
    """At most ONE anchor -- the first _OFFENCE_KEYWORD_ANCHORS pattern
    the question matches -- as a high-confidence statute match. Deliberately
    capped at one: a person's message usually describes a single alleged
    offence, and firing several would recreate the laundry-list problem
    this is meant to fix."""
    for pat, num in _OFFENCE_KEYWORD_ANCHORS:
        if pat.search(question or ""):
            m = _bns_section_as_match(num)
            return [m] if m else []
    return []


def _bns_section_variants(sec_key: str) -> dict:
    """Every BNS_SECTION_DATA entry for a bare section number, keyed by
    subsection (e.g. '318' -> {'318(1)':..., '318(2)':..., '318(3)':...,
    '318(4)':...}), plus the bare key itself if BNS_SECTION_DATA has a
    genuine bare-key entry. Same lookup semantic_retrieval.
    find_relevant_sections() does inline; factored out here so both the
    real-time lookup and _find_cognizable_bailable_mismatches' ground
    truth use the identical logic (no drift between what fed the prompt
    and what verifies the answer)."""
    try:
        from main import BNS_SECTION_DATA
    except ImportError:
        return {}
    exact = BNS_SECTION_DATA.get(sec_key)
    variants = {k: v for k, v in BNS_SECTION_DATA.items()
                if k == sec_key or k.startswith(f"{sec_key}(")}
    if exact is not None and sec_key not in variants:
        variants[sec_key] = exact
    return variants


def _old_code_equivalents(text: str) -> list:
    """Every old IPC/CrPC section number quoted in `text`, paired with its
    modern BNS/BNSS equivalent from statute_concordance (a checked lookup,
    no LLM). Each item: {'old': 'IPC 420', 'new': 'BNS 318(4)',
    'changed': bool} -- or 'new': None for a provision repealed with no
    re-enacted successor. Deduped, in first-seen order. [] if none.

    Thin wrapper over statute_concordance.scan_old_refs (the shared
    primitive, also used by draft_layer.py's templates); kept here for
    format_retrieved_text_for_prompt and app.py's 'what I found' expander,
    both of which import this name."""
    try:
        from statute_concordance import scan_old_refs
    except Exception:
        return []
    return scan_old_refs(text)


def _old_code_refs_note(text: str) -> str:
    """ONE compact line mapping the old IPC/CrPC section numbers quoted in
    `text` to their modern equivalents, or '' if there are none.

    Deliberately terse and non-imperative -- an earlier multi-line,
    "you MUST use the modern number" version measurably crowded other
    points out of the answer (goat-theft eval regressed on the
    grounds-of-arrest / 24-hour checks, 2026-09-02). The generation
    prompt already bars old-code output; this only needs to supply the
    mapping so the model can comply accurately."""
    eqs = _old_code_equivalents(text)
    if not eqs:
        return ""

    def _tidy(new):
        # "BNSS 35(3); BNSS 35(4); BNSS 35(5); BNSS 35(6)" -> "BNSS 35(3)-(6)"
        tgts = new.split("; ")
        acts = {t.split()[0] for t in tgts}
        bares = {t.split()[1].split("(")[0] for t in tgts}
        if len(tgts) > 2 and len(acts) == 1 and len(bares) == 1:
            subs = [t.split("(")[1].rstrip(")") for t in tgts if "(" in t]
            if len(subs) == len(tgts):
                return f"{tgts[0].split()[0]} {bares.pop()}({subs[0]})-({subs[-1]})"
        return new

    live = [f"{e['old']} -> {_tidy(e['new'])}" for e in eqs if e["new"]]
    gone = [e["old"] for e in eqs if e["new"] is None]
    parts = []
    if live:
        parts.append("current equivalents " + ", ".join(live))
    if gone:
        parts.append("not re-enacted: " + ", ".join(gone))
    return ("\n\n[Section-number note (the text above cites the pre-2024 codes): "
            + "; ".join(parts) + "]")


def format_retrieved_text_for_prompt(matches):
    """Formats a list of enriched match dicts (from
    semantic_retrieval.find_relevant_sections) into plain text suitable
    for feeding into generate_grounded_response -- keeps this formatting
    logic in one place rather than duplicated at each call site.

    CONFIRMED REAL BUG CHAIN (2026-08-27), found via a real failed
    answer to "can police arrest directly for cheating?":
    1. Raw BNS statute text (what "text" contains here) does NOT state
       whether an offence is cognizable/non-cognizable -- confirmed by
       reading Section 318's full embedded text directly: it defines
       cheating and its punishment tiers (318(1)-(4)) but never uses the
       words "cognizable" anywhere. That classification lives only in
       the BNSS First Schedule, a separate document cross-referenced to
       build bns_final_merged_table.json -- it was never part of what
       got embedded.
    2. find_relevant_sections() ALREADY fetches this missing information
       correctly, via BNS_SECTION_DATA lookups into each match's
       "section_data" / "all_variants" fields -- but this function
       previously ignored those fields entirely and only passed the raw
       statute text, so the model never received the one fact it needed
       to actually answer the question, even though retrieval had
       already found it.
    Fixed by including each match's structured compliance data (when
    available) alongside its raw text.

    CONFIRMED REAL BUG (2026-08-28), found while wiring in
    statute_doctrine_map.py's curated overrides for BNSS 43(5): this
    function had NO handling for a "context_note" field. Curated
    statute overrides (source="curated_override") carry a hand-verified
    legal nuance in this field -- e.g. the Madurai Bench ruling that
    BNSS 43(5) is directory, not mandatory -- that doesn't exist
    anywhere in the raw statute text itself and can't be derived from
    all_variants (which is BNS_SECTION_DATA compliance-table data, a
    different thing). Without this fix, a curated override's match dict
    passed through this function silently, produced no error, and
    LOST the one piece of information the override existed to add --
    the LLM prompt only ever saw the bare Section 43 text, never the
    curated nuance. Caught by tracing the real function against the
    real dict shape before integration, not discovered via a runtime
    error (there wasn't one -- this was a silent, no-crash omission).
    Fixed by adding an explicit context_note block, kept separate from
    the all_variants block since it's a conceptually different kind of
    addition (hand-written legal nuance vs. structured compliance-table
    data).

    CONFIRMED REAL BUG (2026-08-29), found via a real user question
    ("when can police file charges of attempt to murder"): the
    multi-condition extraction regex (r'less than ([\\d,]+) rupees') was
    written specifically for Section 303's theft threshold and was the
    ONLY extraction pattern this function knew. Section 109(1)'s two
    conditions (a "general" case vs. "if such act causes hurt to any
    person") have NO rupee threshold at all -- the distinction is a
    plain descriptive condition, not a numeric one. Since the regex
    correctly found no match, extracted_facts stayed empty, and the
    code fell through to the generic "a real exception exists that this
    system could not cleanly extract" fallback -- FALSELY implying
    missing information, when the actual condition text
    ("if such act causes hurt to any person") was sitting right there,
    perfectly readable, in raw_text_preview the entire time. This
    produced a confusing, inaccurate response: the model correctly
    described BOTH conditions (10 years general; life imprisonment if
    hurt caused) using the raw statute text, then ALSO added a false
    caveat from this fallback message claiming an exception existed
    that couldn't be captured -- self-contradictory, and confusing for
    a layperson under stress.

    Fixed by generalizing extraction: first try the rupee-threshold
    pattern (Section 303-style), and if that doesn't match, fall back
    to using the condition's own descriptive label directly (Section
    109-style) -- extracting a clean, short version of the actual
    distinguishing fact from raw_text_preview's leading condition
    description, rather than assuming every multi-condition section
    follows the same shape as theft's value exception. The TRUE
    unresolved fallback (genuinely uninterpretable raw_text_preview,
    e.g. garbled beyond any recognizable condition) is now reserved for
    cases where NEITHER pattern extracts anything usable -- not the
    default whenever the specific rupee-regex happens not to match."""
    blocks = []
    for m in matches:
        label = m.get("section_number") or m.get("paragraph_number") or m.get("chunk_id")
        if m.get("case_name"):
            source = m["case_name"]
        elif m.get("act"):
            source = f"{m['act']} Section {label}"
        else:
            source = f"Section {label}"

        block = f"[{source}, Section/Para {label}]\n{m['text']}"

        if m.get("context_note"):
            block += "\n\n[Important legal context for this section]\n" + m["context_note"]

        # PROJECT 2 (citation_currency.py): judgment matches (identified by
        # case_name) get a currency check the same way statute matches get
        # all_variants/context_note enrichment below. This is a lookup only
        # -- the LLM is told the already-decided currency fact and asked to
        # phrase it, exactly like context_note, never asked to judge
        # currency itself.
        if m.get("case_name"):
            from citation_currency import get_citation_currency_for_case_name
            currency_records = get_citation_currency_for_case_name(m["case_name"])
            # Only the PLAIN-LANGUAGE user_facing_note reaches the model
            # here. 'successor_treatment'/'verified_note' are auditor
            # trails (dates, IK tids, "worked example") -- feeding those
            # in produced hand-wringing "treat this judgment with
            # caution" paragraphs in real answers (2026-09-01 eval).
            # GOOD_LAW entries have user_facing_note=None and are skipped.
            notes = [
                r["user_facing_note"] for r in currency_records
                if r["status"] != "GOOD_LAW" and r.get("user_facing_note")
            ]
            if notes:
                block += (
                    "\n\n[Currency note -- if this case is central to your answer, work this "
                    "in as ONE short plain clause; if the case is only a minor mention, you "
                    "may leave it out]\n" + "\n".join(dict.fromkeys(notes))
                )

        variants = m.get("all_variants") or {}
        if variants:
            variant_lines = []
            for variant_key, variant_data in sorted(variants.items()):
                cog = variant_data.get("cognizable")
                bail = variant_data.get("bailable")
                years = variant_data.get("max_years")
                has_multiple = variant_data.get("has_multiple_conditions")
                line = f"  - {variant_key}: cognizable={cog}, bailable={bail}, max_years={years}"
                if has_multiple:
                    conditions = variant_data.get("all_conditions", [])
                    extracted_facts = []
                    for cond in conditions:
                        preview = cond.get("raw_text_preview", "")

                        # PATTERN 1 (original, Section 303-style): a
                        # numeric rupee threshold with an optional
                        # return/restoration qualifier.
                        threshold_match = re.search(r'less than ([\d,]+) rupees', preview)
                        if threshold_match:
                            mentions_return = "return" in preview.lower() or "restoration" in preview.lower()
                            fact = f"if the value of the property is less than Rs. {threshold_match.group(1)}"
                            if mentions_return:
                                fact += " and the property is returned/restored"
                            fact += f", this becomes: cognizable={cond.get('cognizable')}, bailable={cond.get('bailable')}"
                            extracted_facts.append(fact)
                            continue

                        # PATTERN 2 (NEW, Section 109-style): no numeric
                        # threshold, but the condition itself carries a
                        # short, real, plain-language description (e.g.
                        # "If such act causes hurt to any person") --
                        # this is exactly what the "condition" field
                        # already stores for such entries. Use it
                        # directly rather than treating its absence from
                        # Pattern 1 as "nothing could be extracted".
                        condition_desc = cond.get("condition", "")
                        is_generic_label = condition_desc.strip().lower() in ("general", "")
                        if condition_desc and not is_generic_label:
                            # condition_desc can itself be a multi-line
                            # raw preview fragment (confirmed real case:
                            # 109(1)'s second condition's "condition"
                            # field is "If such act causes hurt to\n
                            # Imprisonment for life, or\nCognizable...\n
                            # C" -- truncated mid-word). Take only the
                            # first line, which reliably holds the real
                            # descriptive clause before the punishment/
                            # classification columns begin.
                            first_line = condition_desc.split("\n")[0].strip()
                            if first_line and first_line.lower() != "general":
                                fact = (
                                    f"in the specific situation described as \"{first_line}\", "
                                    f"this becomes: cognizable={cond.get('cognizable')}, "
                                    f"bailable={cond.get('bailable')}"
                                )
                                extracted_facts.append(fact)

                    if extracted_facts:
                        line += (
                            " -- NOTE: this section has multiple conditions, confirmed from the "
                            "source data: " + "; ".join(extracted_facts) + ". State these specific "
                            "conditions as known facts -- do not tell the user these details are "
                            "unavailable or that an exception exists which couldn't be captured, "
                            "since the conditions ARE available and listed here. Do not add any "
                            "OTHER condition beyond what is stated here."
                        )
                    else:
                        # Genuine fallback: multiple conditions exist,
                        # NEITHER extraction pattern found anything
                        # usable in raw_text_preview -- here, and only
                        # here, is uncertainty actually honest.
                        line += (
                            " -- NOTE: this section has MULTIPLE conditions; the above is the "
                            "general-case classification only, and a real exception exists that "
                            "this system could not cleanly extract. Tell the user a specific "
                            "exception exists and to confirm the exact threshold with a lawyer."
                        )
                variant_lines.append(line)
            block += "\n\n[Known classification for this section, from the verified compliance table]\n" + "\n".join(variant_lines)

        blocks.append(block)

    joined = "\n\n---\n\n".join(blocks)
    # ONE consolidated old->new section-number note for the whole prompt
    # (not per-block: the case law repeats "Section 41 CrPC" across
    # several paragraphs, and repeating the mapping each time crowded the
    # answer -- see _old_code_refs_note).
    joined += _old_code_refs_note(joined)
    return joined

def answer_question(question):
    """Main entry point for the chat interface. Returns a dict describing
    the outcome, always including a 'state' field so the UI layer can
    render each case distinctly and honestly, per this project's
    established "surface uncertainty, don't silently guess" principle
    throughout every other retrieval layer built this session.

        Possible states:
      'unrelated'          -- not a legal question, redirected politely
      'covered_elsewhere_in_tool' -- about bank freezing or cheque bounce,
                               which this chat feature's corpus doesn't
                               cover yet, but the wider tool genuinely
                               handles via document upload -- redirected
                               there, not told "not covered"
      'adjacent_uncovered'  -- real legal question, but outside what this
                               tool covers anywhere (BNS/BNSS chat scope
                               or the document-upload domains)
      'classifier_unavailable' -- couldn't even classify the question
      'no_match'           -- in scope, but nothing in the corpus cleared
                               the similarity threshold, AND no curated
                               statute override matched either
      'single_match'       -- one coherent, agreeing set of matches
      'conflicting_matches' -- multiple matches that disagree on a key
                               legal attribute (e.g. cognizability) --
                               never silently picks one
      'retrieval_unavailable' -- embeddings aren't set up (no API key,
                               no embeddings file, etc.)

    FIXED 2026-08-28: the conflicting_matches branch was previously
    nested INSIDE the no_match check's if-block (an indentation bug),
    making it unreachable -- since no_match returns immediately on its
    own condition, the nested conflicting_matches check could only ever
    fire if result["state"] was simultaneously "no_match" AND
    "conflicting_matches", which never happens. Real consequence: a
    genuine conflicting-matches result was silently falling through to
    the single_match handling below, mislabeling a conflict as a clean
    match. Fixed by making conflicting_matches a proper sibling
    elif, checked before the single_match fallthrough.

    ADDED 2026-08-28: a curated statute doctrine override check
    (statute_doctrine_map.py), covering known gaps where semantic
    search under-retrieves a specific high-stakes statute section
    (currently: BNSS 43(5), night-arrest-of-women safeguard, which
    scores ~0.343 against real "arrested at night" queries --
    indistinguishable from the confirmed-irrelevant ceiling ~0.339,
    per this project's own Aug 27 calibration data). This check runs
    BEFORE the normal semantic-search state handling, so it applies
    regardless of what score semantic search assigns -- it's a
    deliberate bypass for specific, known, verified gaps, not a
    replacement for semantic search generally. See
    statute_doctrine_map.py's module docstring for full reasoning and
    scope limits.
    """
    from semantic_retrieval import find_relevant_sections
    from statute_doctrine_map import get_statute_doctrine_override

    category, reasoning, redirect_domain = classify_scope(question)

    if category is None:
        return {"state": "classifier_unavailable"}

    if category == "unrelated":
        return {"state": "unrelated"}

    if category == "covered_elsewhere_in_tool":
        return {"state": "covered_elsewhere_in_tool", "reasoning": reasoning, "redirect_domain": redirect_domain}

    if category == "adjacent_uncovered":
        return {"state": "adjacent_uncovered", "reasoning": reasoning}

    # category == "in_scope" from here on

    # Curated statute override check -- runs BEFORE normal semantic
    # retrieval's state handling, so a known high-stakes gap (like
    # BNSS 43(5)) surfaces even if the embedding score alone wouldn't
    # clear SIMILARITY_THRESHOLD. This does NOT replace semantic
    # search -- both run, and both sets of results get combined below.
    statute_overrides = get_statute_doctrine_override(question)

    # Explicit-section lookup: if the person literally names a section
    # ("what is section 318 of BNS", "does BNS 303 apply"), pull that
    # section's real text directly. Confirmed real gap (2026-09-01 eval):
    # "what is section 318 of BNS" scored below threshold on every
    # embedded chunk and returned no_match -- a plainly answerable
    # question producing an empty answer. Merged into statute_overrides
    # so it flows through the same combine-and-fallback logic below.
    explicit = _explicit_section_matches(question)
    if explicit:
        seen = {(o.get("act"), o.get("section_number")) for o in statute_overrides}
        statute_overrides = statute_overrides + [
            e for e in explicit if (e["act"], e["section_number"]) not in seen
        ]

    # Offence-keyword anchor: only when the person did NOT name a section
    # themselves (explicit lookup already covers that) -- if their message
    # describes an accusation in one plain word ("stole", "cheated"),
    # anchor the matching BNS offence deterministically instead of hoping
    # the embedding ranks it first. Confirmed real gap (2026-09-01 live):
    # "arrested me... saying that i stole a goat" scored Section 303 at
    # ~0.36, behind a procedural noise match. Flows through the same
    # combine-and-fallback logic below as every other statute override.
    if not explicit:
        seen = {(o.get("act"), o.get("section_number")) for o in statute_overrides}
        statute_overrides = statute_overrides + [
            m for m in _offence_keyword_matches(question)
            if (m["act"], m["section_number"]) not in seen
        ]

    result = find_relevant_sections(question)

    if result["state"] == "unavailable":
        # Even if retrieval is unavailable, a curated override may
        # still apply -- don't discard it just because the general
        # embedding-based path is down.
        if statute_overrides:
            retrieved_text = format_retrieved_text_for_prompt(statute_overrides)
            response_text = generate_grounded_response(question, retrieved_text, matches=statute_overrides)
            return {
                "state": "single_match",
                "matches": statute_overrides,
                "response_text": response_text,
            }
        return {"state": "retrieval_unavailable"}

    if result["state"] == "no_match":
        # A curated override can still provide an answer even when
        # normal semantic search found nothing above threshold --
        # this is the exact scenario the override exists for.
        if statute_overrides:
            retrieved_text = format_retrieved_text_for_prompt(statute_overrides)
            response_text = generate_grounded_response(question, retrieved_text, matches=statute_overrides)
            return {
                "state": "single_match",
                "matches": statute_overrides,
                "response_text": response_text,
            }
        return {"state": "no_match"}

    if result["state"] == "conflicting_matches":
        all_matches = result["matches"] + result.get("judgment_matches", []) + statute_overrides
        retrieved_text = format_retrieved_text_for_prompt(all_matches)
        response_text = generate_grounded_response(question, retrieved_text, is_conflict=True, matches=all_matches)
        return {
            "state": "conflicting_matches",
            "matches": all_matches,
            "response_text": response_text,
            "situation_detected": _looks_like_situation(response_text),
        }

    # single_match -- combine statute matches with judgment matches
    # (confirmed real fix: previously judgment_matches were computed by
    # find_relevant_sections but never actually used here, so case law
    # like Arnesh Kumar never reached the response generator even when
    # it was the single highest-scoring result overall) AND any
    # curated statute overrides that matched alongside the normal
    # semantic results.
    all_matches = result["matches"] + result.get("judgment_matches", []) + statute_overrides
    retrieved_text = format_retrieved_text_for_prompt(all_matches)
    response_text = generate_grounded_response(question, retrieved_text, matches=all_matches)
    return {
        "state": "single_match",
        "matches": all_matches,
        "response_text": response_text,
        "situation_detected": _looks_like_situation(response_text),
    }