import json
import re
from anthropic import Anthropic

"""
Chat assistant for laymen asking open-ended questions in plain language.

This is the wiring layer that connects a user's free-text question to the
retrieval infrastructure already built this session -- semantic_retrieval.py
(real embeddings, scored, with conflict detection) and retrieval.py (exact
lookup for judgment doctrines). It does NOT introduce any new way of
deciding legal correctness: every answer either quotes real retrieved text
directly, or is generated by Claude with strict instructions to use ONLY
that retrieved text -- never to answer from general knowledge, never to
invent a section number or holding.

Flow, and why each step exists:
  1. Scope classification (cheap Haiku call) -- decides whether a question
     is plausibly about BNS/BNSS arrest/FIR procedure at all, BEFORE
     spending an embedding call on it. Confirmed necessity: a layman will
     ask genuinely anything ("how do I sue my neighbour", "is this legal",
     small talk) and semantic search always returns SOMETHING, even for
     completely unrelated questions -- classification catches the "this
     isn't even the right kind of question" case before retrieval ever
     runs, rather than relying on the similarity threshold alone to catch
     every kind of irrelevance.
  2. Semantic retrieval (only for in-scope questions) -- real embeddings,
     real similarity scores, real conflict detection (see
     semantic_retrieval.py's docstring for the confirmed "rioting" case
     this specifically guards against).
  3. Response generation -- Claude reads ONLY the retrieved real text and
     is instructed never to go beyond it. This keeps the same
     deterministic-grounding guarantee the rest of this project relies on:
     the LLM explains and phrases, it does not decide or invent.

Every response also carries a plain-language "what to do next" pointer,
per the explicit design goal that this tool should act as a guide/advisor
for a layman, not just answer-and-stop.
"""

import json
from anthropic import Anthropic

try:
    from main import client as _main_client
except ImportError:
    _main_client = None

try:
    import streamlit as st
    _api_key = st.secrets.get("ANTHROPIC_API_KEY")
except Exception:
    _api_key = None

if _main_client is not None:
    client = _main_client
elif _api_key:
    client = Anthropic(api_key=_api_key)
else:
    client = None

HAIKU_MODEL = "claude-haiku-4-5-20251001"

SCOPE_CLASSIFIER_PROMPT = """You are a scope classifier for a legal tool that helps with Indian criminal procedure. This chat feature specifically covers BNS/BNSS arrest, FIR, and police procedure topics, grounded in Arnesh Kumar, D.K. Basu, Vihaan Kumar, Satender Kumar Antil, Youth Bar Association, Prabir Purkayastha, Pankaj Bansal, NALSA, and applying High Court judgments.

The WIDER tool (outside this chat feature, via document upload) ALSO has working, real compliance-check logic for two other domains: bank account freezing (BNS Sections 106/107) and cheque bounce notices (Section 138, Negotiable Instruments Act). This chat feature's own search corpus does not yet include those domains' case law, but the tool as a whole genuinely handles them -- a question about them should be redirected to the document-upload feature, NOT told "this isn't covered" or "consult a lawyer", since that would be inaccurate.

CRITICAL: this chat feature does NOT cover every Indian criminal law. A question can genuinely be about "arrest" or "cognizable/non-cognizable" and still be out of this CHAT feature's scope, if the specific offence involved is governed by a law neither this chat feature nor the wider tool covers (e.g. POCSO, UAPA, NDPS, dowry-specific acts, company/tax law offences). Do NOT classify a question as in_scope just because it uses words like "arrest", "cognizable", "police", or "FIR" -- check whether the SPECIFIC OFFENCE NAMED (if any) is actually a BNS/BNSS offence, a bank-freeze/cheque-bounce matter (see below), or a procedural question with no specific other-law offence attached.

Classify the user's question into exactly one category:

"in_scope" -- plausibly about arrest, FIR, police procedure, bail, or a criminal offence's classification (cognizable/non-cognizable) under BNS/BNSS specifically, where the offence involved (if named) is genuinely a BNS/BNSS offence, or the question is purely about general arrest PROCEDURE with no other-law offence named. Includes vague or layman-phrased questions about "being arrested", "police took my X", "is this a crime", specific BNS offence names (theft, cheating, assault, rioting, etc.), FIR copies, notice before arrest, etc.

"covered_elsewhere_in_tool" -- specifically about bank account freezing (BNS 106/107) or cheque bounce (Section 138 NI Act), including arrest threats or police involvement in either. This wider tool has real, working compliance logic for these via document upload, even though this chat feature's own search corpus does not yet include their case law.

"adjacent_uncovered" -- genuinely about Indian law, but NOT about BNS/BNSS criminal procedure, bank freezing, or cheque bounce. Examples: POCSO, UAPA, NDPS, dowry-specific acts, civil suits, property disputes, family law/divorce, employment law, consumer complaints, contract disputes, tax law, company law offences.

"unrelated" -- not a legal question at all, small talk, or about something with no connection to Indian law (e.g. "what's the weather", "who are you", general chit-chat).

Respond with ONLY a JSON object, no other text:
{{"category": "in_scope" | "covered_elsewhere_in_tool" | "adjacent_uncovered" | "unrelated", "reasoning": "one short sentence"}}

User's question: {question}"""


def classify_scope(question):
    """Returns ('in_scope' | 'covered_elsewhere_in_tool' | 'adjacent_uncovered' | 'unrelated', reasoning)
    or (None, None) if the classifier call itself fails -- callers must
    treat None as an honest 'could not determine', not assume in_scope or
    unrelated by default, since guessing either way here risks either
    wasting a retrieval call on something clearly out of scope, or
    wrongly turning away a genuinely answerable question."""
    if client is None:
        return None, None
    try:
        response = client.messages.create(
            model=HAIKU_MODEL,
            max_tokens=150,
            messages=[{"role": "user", "content": SCOPE_CLASSIFIER_PROMPT.format(question=question)}],
        )
        raw = response.content[0].text.strip()
        # Defensive: strip markdown code fences if the model adds them
        # despite the "ONLY a JSON object" instruction.
        if raw.startswith("```"):
            raw = raw.strip("`")
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()
        parsed = json.loads(raw)
        category = parsed.get("category")
        if category not in ("in_scope", "covered_elsewhere_in_tool", "adjacent_uncovered", "unrelated"):
            return None, None
        return category, parsed.get("reasoning", "")
    except Exception:
        return None, None

RESPONSE_GENERATION_PROMPT = """You are a careful, warm legal guide helping a layperson understand Indian criminal procedure (BNS/BNSS). You are NOT a lawyer and must not give legal advice -- you explain what the law and courts have said, in plain language, and always point the person toward a concrete next step.

CRITICAL RULES, never break these:
- Use ONLY the retrieved text provided below. Do not add facts, section numbers, case holdings, or law/act NAMES from your own general knowledge, even if you're confident they're correct.
- Do NOT refer to the "Indian Penal Code" or "IPC" unless those exact words appear in the retrieved text below. Confirmed real failure: a past response called BNS Section 318 "Section 318 of the Indian Penal Code (BNS)" -- the IPC is a DIFFERENT, older law that BNS replaced; conflating them is factually wrong and this corpus never mentions the IPC. Refer only to the act named in the retrieved text (BNS or BNSS).
- If the retrieved text doesn't fully answer the question, say so honestly rather than filling the gap.
- Never state a compliance verdict (like "this is legal" or "this is illegal") -- you can explain what the law says, but whether it applies to the person's specific situation requires facts you don't have.
- Always end with a short, concrete "what you can do next" suggestion (e.g. "if you have a copy of the FIR, you could upload it here for a full check", or "a lawyer could confirm which of these applies to your situation").
- Keep the tone warm and plain -- avoid legal jargon where you can, and explain any term you must use.
- When you name a section, ALWAYS include its exact subsection number if the retrieved text distinguishes between subsections (e.g. write "Section 318(4)", not just "Section 318") -- confirmed real failure: describing 318(4)'s punishment without ever naming it as 318(4) specifically, making it impossible for the reader to verify which provision was meant.
{conflict_instruction}

The person's question: {question}

Retrieved information (this is REAL text from Indian statutes and court judgments -- use only this):
{retrieved_text}

Write a short, clear, warm answer, followed by a "What you can do next" line."""

_CONFLICT_INSTRUCTION = """- IMPORTANT: the retrieved sections genuinely DISAGREE with each other on a key point (e.g. some are arrestable without a warrant, others are not). Do NOT blend them into one narrative paragraph. Structure your answer as clearly separated scenarios, each labeled with its exact section number, e.g.:
  "**If [scenario 1, naming the exact section]:** [what applies]"
  "**If [scenario 2, naming the exact section]:** [what applies]"
  Make the fork in the law visually obvious, not something the reader has to infer from careful reading."""


def generate_grounded_response(question, retrieved_text, is_conflict=False):
    """Generates a plain-language answer using ONLY the given retrieved
    text. Returns None if the generation call fails -- callers should
    fall back to showing the raw retrieved text directly rather than
    inventing a summary.

    is_conflict: set True when called for a 'conflicting_matches' result,
    so the prompt explicitly instructs the model to structure its answer
    as separated scenarios rather than blending disagreeing provisions
    into one narrative -- confirmed real failure: a genuine
    conflicting_matches case (cheating: 318(1) non-arrestable vs 318(4)
    arrestable) was answered as a single fluent paragraph that only
    named one subsection explicitly, hiding the fork in the law the
    conflicting_matches state exists specifically to surface."""
    if client is None:
        return None
    try:
        conflict_instruction = _CONFLICT_INSTRUCTION if is_conflict else ""
        response = client.messages.create(
            model=HAIKU_MODEL,
            max_tokens=700,
            messages=[{
                "role": "user",
                "content": RESPONSE_GENERATION_PROMPT.format(
                    question=question, retrieved_text=retrieved_text,
                    conflict_instruction=conflict_instruction,
                ),
            }],
        )
        return response.content[0].text.strip()
    except Exception:
        return None


def format_retrieved_text_for_prompt(matches):
    """Formats a list of enriched match dicts (from
    semantic_retrieval.find_relevant_sections) into plain text suitable
    for feeding into generate_grounded_response -- keeps this formatting
    logic in one place rather than duplicated at each call site.

    CONFIRMED REAL BUG CHAIN (2026-08-27), found via a real failed
    answer to "can police arrest directly for cheating?":
    1. Raw BNS statute text (what "text" contains here) does NOT state
       whether an offence is cognizable/non-cognizable -- confirmed by
       reading Section 318's full embedded text directly: it defines
       cheating and its punishment tiers (318(1)-(4)) but never uses the
       words "cognizable" anywhere. That classification lives only in
       the BNSS First Schedule, a separate document cross-referenced to
       build bns_final_merged_table.json -- it was never part of what
       got embedded.
    2. find_relevant_sections() ALREADY fetches this missing information
       correctly, via BNS_SECTION_DATA lookups into each match's
       "section_data" / "all_variants" fields -- but this function
       previously ignored those fields entirely and only passed the raw
       statute text, so the model never received the one fact it needed
       to actually answer the question, even though retrieval had
       already found it.
    Fixed by including each match's structured compliance data (when
    available) alongside its raw text."""
    blocks = []
    for m in matches:
        label = m.get("section_number") or m.get("paragraph_number") or m.get("chunk_id")
        if m.get("case_name"):
            source = m["case_name"]
        elif m.get("act"):
            source = f"{m['act']} Section {label}"
        else:
            source = f"Section {label}"

        block = f"[{source}, Section/Para {label}]\n{m['text']}"

        variants = m.get("all_variants") or {}
        if variants:
            variant_lines = []
            for variant_key, variant_data in sorted(variants.items()):
                cog = variant_data.get("cognizable")
                bail = variant_data.get("bailable")
                years = variant_data.get("max_years")
                has_multiple = variant_data.get("has_multiple_conditions")
                line = f"  - {variant_key}: cognizable={cog}, bailable={bail}, max_years={years}"
                if has_multiple:
                    # CONFIRMED REAL BUG, FIXED IN TWO STEPS (2026-08-27):
                    # Step 1 found that has_multiple_conditions sections
                    # (e.g. theft's value-based exception) were silently
                    # omitted entirely -- fixed by flagging that an
                    # exception exists.
                    # Step 2, this fix: the flagging text said the exact
                    # threshold "isn't accessible", which the user
                    # correctly caught as FALSE -- the real Rs.5,000
                    # threshold and the "upon return of property"
                    # condition ARE cleanly present in
                    # all_conditions[]['raw_text_preview'], just scrambled
                    # in LINE ORDER (a PDF table-extraction artifact), not
                    # actually missing. Confirmed by direct regex
                    # extraction: the threshold is reliably recoverable.
                    # Only genuinely un-recoverable details (e.g. exact
                    # wording of "first offense" style qualifiers, if any
                    # exist beyond what's extracted) should be flagged as
                    # uncertain -- not facts that are simply reachable via
                    # this extraction.
                    conditions = variant_data.get("all_conditions", [])
                    extracted_facts = []
                    for cond in conditions:
                        preview = cond.get("raw_text_preview", "")
                        threshold_match = re.search(r'less than ([\d,]+) rupees', preview)
                        mentions_return = "return" in preview.lower() or "restoration" in preview.lower()
                        if threshold_match:
                            fact = f"if the value of the property is less than Rs. {threshold_match.group(1)}"
                            if mentions_return:
                                fact += " and the property is returned/restored"
                            fact += f", this becomes: cognizable={cond.get('cognizable')}, bailable={cond.get('bailable')}"
                            extracted_facts.append(fact)
                    if extracted_facts:
                        line += (
                            " -- NOTE: this section has a value-based exception, confirmed from the "
                            "source data: " + "; ".join(extracted_facts) + ". State this specific "
                            "threshold as a known fact -- do not tell the user this detail is "
                            "unavailable, since it is available. Do not add any OTHER condition "
                            "(such as 'first offense') that is not stated here."
                        )
                    else:
                        # Genuine fallback: multiple conditions exist but
                        # this system couldn't cleanly extract the specific
                        # threshold -- here, and only here, is uncertainty
                        # actually honest.
                        line += (
                            " -- NOTE: this section has MULTIPLE conditions; the above is the "
                            "general-case classification only, and a real exception exists that "
                            "this system could not cleanly extract. Tell the user a specific "
                            "exception exists and to confirm the exact threshold with a lawyer."
                        )
                variant_lines.append(line)
            block += "\n\n[Known classification for this section, from the verified compliance table]\n" + "\n".join(variant_lines)

        blocks.append(block)
    return "\n\n---\n\n".join(blocks)


def answer_question(question):
    """Main entry point for the chat interface. Returns a dict describing
    the outcome, always including a 'state' field so the UI layer can
    render each case distinctly and honestly, per this project's
    established "surface uncertainty, don't silently guess" principle
    throughout every other retrieval layer built this session.

        Possible states:
      'unrelated'          -- not a legal question, redirected politely
      'covered_elsewhere_in_tool' -- about bank freezing or cheque bounce,
                               which this chat feature's corpus doesn't
                               cover yet, but the wider tool genuinely
                               handles via document upload -- redirected
                               there, not told "not covered"
      'adjacent_uncovered'  -- real legal question, but outside what this
                               tool covers anywhere (BNS/BNSS chat scope
                               or the document-upload domains)
      'classifier_unavailable' -- couldn't even classify the question
      'no_match'           -- in scope, but nothing in the corpus cleared
                               the similarity threshold
      'single_match'       -- one coherent, agreeing set of matches
      'conflicting_matches' -- multiple matches that disagree on a key
                               legal attribute (e.g. cognizability) --
                               never silently picks one
      'retrieval_unavailable' -- embeddings aren't set up (no API key,
                               no embeddings file, etc.)
    """
    from semantic_retrieval import find_relevant_sections

    category, reasoning = classify_scope(question)

    if category is None:
        return {"state": "classifier_unavailable"}

    if category == "unrelated":
        return {"state": "unrelated"}

    if category == "covered_elsewhere_in_tool":
        return {"state": "covered_elsewhere_in_tool", "reasoning": reasoning}

    if category == "adjacent_uncovered":
        return {"state": "adjacent_uncovered", "reasoning": reasoning}

    # category == "in_scope" from here on
    result = find_relevant_sections(question)

    if result["state"] == "unavailable":
        return {"state": "retrieval_unavailable"}

    if result["state"] == "no_match":
        return {"state": "no_match"}

        if result["state"] == "conflicting_matches":
            all_matches = result["matches"] + result.get("judgment_matches", [])
            retrieved_text = format_retrieved_text_for_prompt(all_matches)
            response_text = generate_grounded_response(question, retrieved_text, is_conflict=True)
            return {
                        "state": "conflicting_matches",
                        "matches": all_matches,
                        "response_text": response_text,
            }
        
        

    # single_match -- combine statute matches with judgment matches
    # (confirmed real fix: previously judgment_matches were computed by
    # find_relevant_sections but never actually used here, so case law
    # like Arnesh Kumar never reached the response generator even when
    # it was the single highest-scoring result overall)
    all_matches = result["matches"] + result.get("judgment_matches", [])
    retrieved_text = format_retrieved_text_for_prompt(all_matches)
    response_text = generate_grounded_response(question, retrieved_text)
    return {
        "state": "single_match",
        "matches": all_matches,
        "response_text": response_text,
    }
    
    
    