import json
import re
from anthropic import Anthropic

"""
Chat assistant for laymen asking open-ended questions in plain language.

This is the wiring layer that connects a user's free-text question to the
retrieval infrastructure already built this session -- semantic_retrieval.py
(real embeddings, scored, with conflict detection) and retrieval.py (exact
lookup for judgment doctrines). It does NOT introduce any new way of
deciding legal correctness: every answer either quotes real retrieved text
directly, or is generated by Claude with strict instructions to use ONLY
that retrieved text -- never to answer from general knowledge, never to
invent a section number or holding.

Flow, and why each step exists:
  1. Scope classification (cheap Haiku call) -- decides whether a question
     is plausibly about BNS/BNSS arrest/FIR procedure at all, BEFORE
     spending an embedding call on it. Confirmed necessity: a layman will
     ask genuinely anything ("how do I sue my neighbour", "is this legal",
     small talk) and semantic search always returns SOMETHING, even for
     completely unrelated questions -- classification catches the "this
     isn't even the right kind of question" case before retrieval ever
     runs, rather than relying on the similarity threshold alone to catch
     every kind of irrelevance.
  2. Semantic retrieval (only for in-scope questions) -- real embeddings,
     real similarity scores, real conflict detection (see
     semantic_retrieval.py's docstring for the confirmed "rioting" case
     this specifically guards against).
  3. Response generation -- Claude reads ONLY the retrieved real text and
     is instructed never to go beyond it. This keeps the same
     deterministic-grounding guarantee the rest of this project relies on:
     the LLM explains and phrases, it does not decide or invent.
     CONFIRMED (2026-09-01) the instruction alone is not a hard
     guarantee -- a real, low-frequency (~1/10 trials) case slipped
     through where the model named a real BNSS section it was never
     actually given for that query. generate_grounded_response() now
     deterministically checks its own output against retrieved_text
     (see _find_ungrounded_sections) and retries once before ever
     showing an unverified claim -- the LLM proposes, Python verifies.

Every response also carries a plain-language "what to do next" pointer,
per the explicit design goal that this tool should act as a guide/advisor
for a layman, not just answer-and-stop.
"""

import json
from anthropic import Anthropic

try:
    from main import client as _main_client
except ImportError:
    _main_client = None

try:
    import streamlit as st
    _api_key = st.secrets.get("ANTHROPIC_API_KEY")
except Exception:
    _api_key = None

if _main_client is not None:
    client = _main_client
elif _api_key:
    client = Anthropic(api_key=_api_key)
else:
    client = None
    


#HAIKU_MODEL = "claude-haiku-4-5-20251001"
SONNET_MODEL = "claude-sonnet-5"  # per this environment's current model list


SCOPE_CLASSIFIER_PROMPT = """You are a scope classifier for a legal tool that helps with Indian criminal procedure. This chat feature specifically covers BNS/BNSS arrest, FIR, and police procedure topics, grounded in Arnesh Kumar, D.K. Basu, Vihaan Kumar, Satender Kumar Antil, Youth Bar Association, Prabir Purkayastha, Pankaj Bansal, NALSA, and applying High Court judgments.

The WIDER tool (outside this chat feature, via document upload) ALSO has working, real compliance-check logic for two other domains: bank account freezing (BNS Sections 106/107) and cheque bounce notices (Section 138, Negotiable Instruments Act). This chat feature's own search corpus does not yet include those domains' case law, but the tool as a whole genuinely handles them -- a question about them should be redirected to the document-upload feature, NOT told "this isn't covered" or "consult a lawyer", since that would be inaccurate.

CRITICAL: this chat feature does NOT cover every Indian criminal law. A question can genuinely be about "arrest" or "cognizable/non-cognizable" and still be out of this CHAT feature's scope, if the specific offence involved is governed by a law neither this chat feature nor the wider tool covers (e.g. POCSO, UAPA, NDPS, dowry-specific acts, company/tax law offences). Do NOT classify a question as in_scope just because it uses words like "arrest", "cognizable", "police", or "FIR" -- check whether the SPECIFIC OFFENCE NAMED (if any) is actually a BNS/BNSS offence, a bank-freeze/cheque-bounce matter (see below), or a procedural question with no specific other-law offence attached.

Classify the user's question into exactly one category:

"in_scope" -- plausibly about arrest, FIR, police procedure, bail, or a criminal offence's classification (cognizable/non-cognizable) under BNS/BNSS specifically, where the offence involved (if named) is genuinely a BNS/BNSS offence, or the question is purely about general arrest PROCEDURE with no other-law offence named. Includes vague or layman-phrased questions about "being arrested", "police took my X", "is this a crime", specific BNS offence names (theft, cheating, assault, rioting, etc.), FIR copies, notice before arrest, etc.

"covered_elsewhere_in_tool" -- specifically about bank account freezing (BNS 106/107) or cheque bounce (Section 138 NI Act), including arrest threats or police involvement in either. This wider tool has real, working compliance logic for these via document upload, even though this chat feature's own search corpus does not yet include their case law.

"adjacent_uncovered" -- genuinely about Indian law, but NOT about BNS/BNSS criminal procedure, bank freezing, or cheque bounce. Examples: POCSO, UAPA, NDPS, dowry-specific acts, civil suits, property disputes, family law/divorce, employment law, consumer complaints, contract disputes, tax law, company law offences.

"unrelated" -- not a legal question at all, small talk, or about something with no connection to Indian law (e.g. "what's the weather", "who are you", general chit-chat).

If (and only if) the category is "covered_elsewhere_in_tool", also decide which specific domain: "freeze" (bank account freezing) or "cheque_bounce" (Section 138 NI Act cheque dishonour). For every other category, redirect_domain must be null.

Respond with ONLY a JSON object, no other text:
{{"category": "in_scope" | "covered_elsewhere_in_tool" | "adjacent_uncovered" | "unrelated", "redirect_domain": "freeze" | "cheque_bounce" | null, "reasoning": "one short sentence"}}

User's question: {question}"""

def _extract_text_from_response(response):
    """Shared helper: safely extracts text content from an Anthropic
    API response, regardless of block order or the presence of
    non-text blocks (e.g. ThinkingBlock).
 
    FIXED 2026-08-29: every call site in this project previously did
    `response.content[0].text`, assuming the first content block is
    always plain text. CONFIRMED REAL FAILURE (in layman_summary.py,
    same bug class, same session): 'ThinkingBlock' object has no
    attribute 'text' -- for a sufficiently complex prompt, the model
    can return a ThinkingBlock as the first content item, followed by
    the actual TextBlock.

    CORRECTION (2026-09-01): this docstring already claimed the helper
    was "applied here defensively to both call sites in this file" --
    that was FALSE. All three real call sites in this file
    (classify_scope, and both the original + retry calls in
    generate_grounded_response) still did raw `.content[0].text.strip()`
    right below this very function, never actually calling it. CONFIRMED
    REAL FAILURE, found via live user testing: exactly this crash
    ('ThinkingBlock' object has no attribute 'text') fired inside
    generate_grounded_response's try/except, was silently swallowed,
    and returned None -- which the caller correctly falls back on, but
    the actual cause (a client bug, not "generation genuinely failed")
    was invisible. Now actually wired into all three call sites."""
    text_block = next((block for block in response.content if hasattr(block, "text")), None)
    if text_block is None:
        raise ValueError("No text block found in response.content -- only non-text blocks returned.")
    return text_block.text


def classify_scope(question):
    """Returns ('in_scope' | 'covered_elsewhere_in_tool' | 'adjacent_uncovered' | 'unrelated',
    reasoning, redirect_domain) or (None, None, None) if the classifier call itself fails --
    callers must treat None as an honest 'could not determine', not assume in_scope or
    unrelated by default, since guessing either way here risks either
    wasting a retrieval call on something clearly out of scope, or
    wrongly turning away a genuinely answerable question.

    redirect_domain: ADDED 2026-09-01, only meaningful when category is
    'covered_elsewhere_in_tool' -- 'freeze' or 'cheque_bounce', naming
    which of the two dedicated free-text interview flows
    (freeze_interview_flow.py / cheque_bounce_interview_flow.py) the
    question actually belongs to, so the app can hand the user's
    already-typed question straight to the RIGHT flow with one click
    instead of a generic 'go upload a document' dead end. None for
    every other category, and None (not a guess) if the model omits it
    or returns something unrecognised for a covered_elsewhere_in_tool
    response -- the app must be able to fall back to a domain-less
    redirect rather than launching the wrong interview flow."""
    if client is None:
        return None, None, None
    try:
        response = client.messages.create(
            model=SONNET_MODEL,
            max_tokens=1500,
            messages=[{"role": "user", "content": SCOPE_CLASSIFIER_PROMPT.format(question=question)}],
        )
        raw = _extract_text_from_response(response).strip()
        # Defensive: strip markdown code fences if the model adds them
        # despite the "ONLY a JSON object" instruction.
        if raw.startswith("```"):
            raw = raw.strip("`")
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()
        parsed = json.loads(raw)
        category = parsed.get("category")
        if category not in ("in_scope", "covered_elsewhere_in_tool", "adjacent_uncovered", "unrelated"):
            return None, None, None
        redirect_domain = parsed.get("redirect_domain")
        if category != "covered_elsewhere_in_tool" or redirect_domain not in ("freeze", "cheque_bounce"):
            redirect_domain = None
        return category, parsed.get("reasoning", ""), redirect_domain
    except Exception:
        return None, None, None

RESPONSE_GENERATION_PROMPT = """You are a careful, warm legal guide helping a layperson understand Indian criminal procedure (BNS/BNSS). You are NOT a lawyer and must not give legal advice -- you explain what the law and courts have said, in plain language, and always point the person toward a concrete next step.

CRITICAL RULES, never break these:
- Use ONLY the information provided below. Do not add facts, section numbers, case holdings, or law/act NAMES from your own general knowledge, even if you're confident they're correct.
- Do NOT refer to the "Indian Penal Code" or "IPC" unless those exact words appear in the information below. Confirmed real failure: a past response called BNS Section 318 "Section 318 of the Indian Penal Code (BNS)" -- the IPC is a DIFFERENT, older law that BNS replaced; conflating them is factually wrong and this corpus never mentions the IPC. Refer only to the act named in the information below (BNS or BNSS).
- NEVER use the words "retrieved text", "the text I have", "the retrieved information", "the classification table", "the compliance table", or any other phrase describing WHERE this information came from. The person reading this is a layperson, often under real stress -- they should never see the internal machinery behind the answer. Just state the law directly: write "Section 303 covers..." not "the retrieved text shows Section 303 covers...". If something isn't covered, say "I don't have information on..." not "the retrieved text doesn't include...".
- If the information below doesn't fully answer the question, say so honestly rather than filling the gap -- but ONLY flag genuine gaps. CONFIRMED REAL FAILURE (2026-08-28): given Section 109(1) where the underlying data showed a general punishment (10 years) versus an enhanced one (life imprisonment, if the act causes hurt) -- both of which were correctly and specifically stated in the answer -- the response THEN added an extra, confusing caveat calling this a "flagged exception... that couldn't be cleanly extracted," implying missing information that did not actually exist. If you have already stated the specific facts clearly (e.g. "the punishment is X, or Y if Z happens"), do NOT also add a vaguer follow-up caveat suggesting the details are incomplete or that "a lawyer should confirm the exact condition" -- you already stated the exact condition. Only flag genuine uncertainty when you are ACTUALLY missing a specific fact you cannot state, not as a reflexive hedge after already answering completely.
- Never state a compliance verdict (like "this is legal" or "this is illegal") -- you can explain what the law says, but whether it applies to the person's specific situation requires facts you don't have.
- Always end with a short, concrete "what you can do next" suggestion (e.g. "if you have a copy of the FIR, you could upload it here for a full check", or "a lawyer could confirm which of these applies to your situation"). Include this only ONCE, at the very end -- do not repeat a "what you can do next" section twice.
- Keep the tone warm and plain -- avoid legal jargon where you can, and explain any term you must use.
- When you name a section, ALWAYS include its exact subsection number if the information distinguishes between subsections (e.g. write "Section 318(4)", not just "Section 318") -- confirmed real failure: describing 318(4)'s punishment without ever naming it as 318(4) specifically, making it impossible for the reader to verify which provision was meant.
- MANDATORY: if ANY statute section (BNS or BNSS) appears in the information below, you MUST explicitly name and briefly describe every single one of them in your answer, even if a court judgment is also present and even if the statute text seems less directly relevant than the judgment. Do not let a rich, narrative judgment crowd out plainer statute text -- the statute sections are usually the MOST directly relevant answer to "what does the law say about my situation," since they define the actual offence, while judgments typically speak to arrest PROCEDURE more generally. Address the statute sections FIRST, by name, before discussing any judgment. EXCEPTION: if a section is clearly not relevant to the person's actual question (e.g. a general procedural section about how a Magistrate frames charges, when the person is asking about the threshold for filing a charge), you may briefly note it doesn't seem to apply rather than describing it in full -- do not force an irrelevant section into the main explanation just because it was among the retrieved candidates.
{conflict_instruction}

The person's question: {question}

Here is the real legal information relevant to this question (statute text and court judgments) -- use only this, and present it as your own direct knowledge of the law, never as something you were "given" or "retrieved":
{retrieved_text}

Write a short, clear, warm answer, followed by a single "What you can do next" line at the end."""


_CONFLICT_INSTRUCTION = """- IMPORTANT: the sections below genuinely DISAGREE with each other on a key point (e.g. some are arrestable without a warrant, others are not). Do NOT blend them into one narrative paragraph. Structure your answer as clearly separated scenarios, each labeled with its exact section number, e.g.:
  "**If [scenario 1, naming the exact section]:** [what applies]"
  "**If [scenario 2, naming the exact section]:** [what applies]"
  Make the fork in the law visually obvious, not something the reader has to infer from careful reading."""
  
  
# ---------------------------------------------------------------------
# REPLACE generate_grounded_response with this version -- adds an
# optional `model` parameter, defaulting to HAIKU_MODEL so every
# existing call site (answer_question, which never passes `model`)
# behaves EXACTLY as before. Only a test script that explicitly passes
# model=SONNET_MODEL will use the stronger model. This is deliberately
# non-invasive: no production behavior changes until you decide to
# change answer_question's calls, which this does NOT do.
# ---

_SECTION_REFERENCE_PATTERN = re.compile(r"\bSection\s+(\d+)", re.IGNORECASE)


def _extract_section_numbers(text: str) -> set:
    """Returns the set of base section numbers (e.g. '274' from 'Section
    274(2)') referenced anywhere in text. Base number only -- subsection
    suffixes are stripped since retrieved_text's own labels are also
    base-number-only (see get_statute_section's docstring)."""
    return {m.group(1) for m in _SECTION_REFERENCE_PATTERN.finditer(text or "")}


def _find_ungrounded_sections(response_text: str, retrieved_text: str) -> list:
    """CONFIRMED REAL BUG (2026-09-01), found via live user testing: asked
    'police came to my house and arrested me directly saying that i stole
    a goat', the model's answer confidently named 'Section 274 of the
    BNSS' (summons-case procedure) with an accurate description of its
    real text -- but Section 274 never appeared anywhere in retrieved_text
    for that query. Reproduced the exact same question+retrieved_text
    pair 9 more times: 0/9 repeated the hallucination, confirming this is
    a real but LOW-FREQUENCY, STOCHASTIC failure of the "use ONLY the
    information provided" instruction in RESPONSE_GENERATION_PROMPT, not
    a deterministic bug -- explicitly ruled out citation_currency.py's
    prompt injection as the cause (identical hallucination rate with and
    without it, across the same trials). The section named was REAL and
    accurately described (confirmed via retrieval.get_statute_section)
    -- this is the model drawing on its own training knowledge of actual
    Indian law, not inventing fiction, which makes it MORE dangerous to
    silently trust, not less: a fabricated-sounding claim is easier to
    doubt than a lucid, textually-perfect, but ungrounded-for-THIS-query
    one. Since no prompt wording can be proven to eliminate a stochastic
    LLM failure, this is a deterministic Python safety net instead --
    the same discipline as the rest of this project: verify the claim
    against real source text before it reaches the user, never trust
    confidence alone. A false positive here (a real section mentioned in
    retrieved_text but phrased differently, e.g. digits embedded in a
    citation like '(2000) 2 SCC 380') is possible but rare and safe --
    it only triggers one retry, not a hard failure.

    Returns the sorted list of section numbers response_text references
    that do not appear anywhere (as a plain substring) in retrieved_text.
    Empty list means nothing to worry about -- the common case."""
    referenced = _extract_section_numbers(response_text)
    if not referenced:
        return []
    return sorted(num for num in referenced if num not in retrieved_text)


_UNGROUNDED_RETRY_INSTRUCTION = """
IMPORTANT CORRECTION: your previous answer to this exact question referenced Section(s) {sections}, but none of those section numbers appear anywhere in the information provided above. Do not mention Section(s) {sections} at all in your new answer, even if you are confident they are real and relevant -- only use section numbers that literally appear in the information above. Write a new, complete answer from scratch, following all the same rules."""


def generate_grounded_response(question, retrieved_text, is_conflict=False, model=SONNET_MODEL):
    """Generates a plain-language answer using ONLY the given retrieved
    text. Returns None if the generation call fails -- callers should
    fall back to showing the raw retrieved text directly rather than
    inventing a summary.
 
    is_conflict: set True when called for a 'conflicting_matches' result,
    so the prompt explicitly instructs the model to structure its answer
    as separated scenarios rather than blending disagreeing provisions
    into one narrative -- confirmed real failure: a genuine
    conflicting_matches case (cheating: 318(1) non-arrestable vs 318(4)
    arrestable) was answered as a single fluent paragraph that only
    named one subsection explicitly, hiding the fork in the law the
    conflicting_matches state exists specifically to surface.
 
    model: ADDED 2026-08-28 for a deliberate, evidence-gated Haiku-vs-
    Sonnet comparison. CORRECTION (2026-09-01): this docstring previously
    claimed the default was HAIKU_MODEL "so this parameter is 100%
    backward compatible" -- that was already false when written: line 64
    has HAIKU_MODEL commented out entirely, and the actual default
    parameter value above is SONNET_MODEL. Every call site (answer_question
    never passes model) has been running on Sonnet, not Haiku. Corrected
    here rather than left stale.

    GROUNDING VERIFICATION (added 2026-09-01): after generating a
    response, checks every "Section N" it names against retrieved_text
    via _find_ungrounded_sections() -- see that function's docstring for
    the confirmed real hallucination this guards against (a real,
    accurately-described BNSS section, but one that was never actually
    retrieved for the query at hand). If ungrounded sections are found,
    retries ONCE with an explicit correction naming them. If the retry
    is still ungrounded, returns None -- the same "give up honestly"
    signal already used for a failed API call, so callers fall back to
    showing the raw retrieved text rather than ever displaying a claim
    that could not be verified against what was actually retrieved."""
    if client is None:
        return None
    try:
        conflict_instruction = _CONFLICT_INSTRUCTION if is_conflict else ""
        prompt = RESPONSE_GENERATION_PROMPT.format(
            question=question, retrieved_text=retrieved_text,
            conflict_instruction=conflict_instruction,
        )
        response = client.messages.create(
            model=model,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
        )
        response_text = _extract_text_from_response(response).strip()

        ungrounded = _find_ungrounded_sections(response_text, retrieved_text)
        if ungrounded:
            retry_prompt = prompt + _UNGROUNDED_RETRY_INSTRUCTION.format(
                sections=", ".join(ungrounded)
            )
            retry_response = client.messages.create(
                model=model,
                max_tokens=1500,
                messages=[{"role": "user", "content": retry_prompt}],
            )
            retry_text = _extract_text_from_response(retry_response).strip()
            if _find_ungrounded_sections(retry_text, retrieved_text):
                return None
            return retry_text

        return response_text
    except Exception:
        return None


def format_retrieved_text_for_prompt(matches):
    """Formats a list of enriched match dicts (from
    semantic_retrieval.find_relevant_sections) into plain text suitable
    for feeding into generate_grounded_response -- keeps this formatting
    logic in one place rather than duplicated at each call site.

    CONFIRMED REAL BUG CHAIN (2026-08-27), found via a real failed
    answer to "can police arrest directly for cheating?":
    1. Raw BNS statute text (what "text" contains here) does NOT state
       whether an offence is cognizable/non-cognizable -- confirmed by
       reading Section 318's full embedded text directly: it defines
       cheating and its punishment tiers (318(1)-(4)) but never uses the
       words "cognizable" anywhere. That classification lives only in
       the BNSS First Schedule, a separate document cross-referenced to
       build bns_final_merged_table.json -- it was never part of what
       got embedded.
    2. find_relevant_sections() ALREADY fetches this missing information
       correctly, via BNS_SECTION_DATA lookups into each match's
       "section_data" / "all_variants" fields -- but this function
       previously ignored those fields entirely and only passed the raw
       statute text, so the model never received the one fact it needed
       to actually answer the question, even though retrieval had
       already found it.
    Fixed by including each match's structured compliance data (when
    available) alongside its raw text.

    CONFIRMED REAL BUG (2026-08-28), found while wiring in
    statute_doctrine_map.py's curated overrides for BNSS 43(5): this
    function had NO handling for a "context_note" field. Curated
    statute overrides (source="curated_override") carry a hand-verified
    legal nuance in this field -- e.g. the Madurai Bench ruling that
    BNSS 43(5) is directory, not mandatory -- that doesn't exist
    anywhere in the raw statute text itself and can't be derived from
    all_variants (which is BNS_SECTION_DATA compliance-table data, a
    different thing). Without this fix, a curated override's match dict
    passed through this function silently, produced no error, and
    LOST the one piece of information the override existed to add --
    the LLM prompt only ever saw the bare Section 43 text, never the
    curated nuance. Caught by tracing the real function against the
    real dict shape before integration, not discovered via a runtime
    error (there wasn't one -- this was a silent, no-crash omission).
    Fixed by adding an explicit context_note block, kept separate from
    the all_variants block since it's a conceptually different kind of
    addition (hand-written legal nuance vs. structured compliance-table
    data).

    CONFIRMED REAL BUG (2026-08-29), found via a real user question
    ("when can police file charges of attempt to murder"): the
    multi-condition extraction regex (r'less than ([\\d,]+) rupees') was
    written specifically for Section 303's theft threshold and was the
    ONLY extraction pattern this function knew. Section 109(1)'s two
    conditions (a "general" case vs. "if such act causes hurt to any
    person") have NO rupee threshold at all -- the distinction is a
    plain descriptive condition, not a numeric one. Since the regex
    correctly found no match, extracted_facts stayed empty, and the
    code fell through to the generic "a real exception exists that this
    system could not cleanly extract" fallback -- FALSELY implying
    missing information, when the actual condition text
    ("if such act causes hurt to any person") was sitting right there,
    perfectly readable, in raw_text_preview the entire time. This
    produced a confusing, inaccurate response: the model correctly
    described BOTH conditions (10 years general; life imprisonment if
    hurt caused) using the raw statute text, then ALSO added a false
    caveat from this fallback message claiming an exception existed
    that couldn't be captured -- self-contradictory, and confusing for
    a layperson under stress.

    Fixed by generalizing extraction: first try the rupee-threshold
    pattern (Section 303-style), and if that doesn't match, fall back
    to using the condition's own descriptive label directly (Section
    109-style) -- extracting a clean, short version of the actual
    distinguishing fact from raw_text_preview's leading condition
    description, rather than assuming every multi-condition section
    follows the same shape as theft's value exception. The TRUE
    unresolved fallback (genuinely uninterpretable raw_text_preview,
    e.g. garbled beyond any recognizable condition) is now reserved for
    cases where NEITHER pattern extracts anything usable -- not the
    default whenever the specific rupee-regex happens not to match."""
    blocks = []
    for m in matches:
        label = m.get("section_number") or m.get("paragraph_number") or m.get("chunk_id")
        if m.get("case_name"):
            source = m["case_name"]
        elif m.get("act"):
            source = f"{m['act']} Section {label}"
        else:
            source = f"Section {label}"

        block = f"[{source}, Section/Para {label}]\n{m['text']}"

        if m.get("context_note"):
            block += "\n\n[Important legal context for this section]\n" + m["context_note"]

        # PROJECT 2 (citation_currency.py): judgment matches (identified by
        # case_name) get a currency check the same way statute matches get
        # all_variants/context_note enrichment below. This is a lookup only
        # -- the LLM is told the already-decided currency fact and asked to
        # phrase it, exactly like context_note, never asked to judge
        # currency itself.
        if m.get("case_name"):
            from citation_currency import get_citation_currency_for_case_name
            currency_records = get_citation_currency_for_case_name(m["case_name"])
            non_good_law = [r for r in currency_records if r["status"] != "GOOD_LAW"]
            if non_good_law:
                lines = []
                for r in non_good_law:
                    lines.append(f"Status: {r['status']}.")
                    if r.get("successor_treatment"):
                        lines.append(r["successor_treatment"])
                    elif r.get("verified_note"):
                        lines.append(r["verified_note"])
                block += (
                    "\n\n[Citation currency note -- state this plainly, do not soften or omit it]\n"
                    + "\n".join(lines)
                )

        variants = m.get("all_variants") or {}
        if variants:
            variant_lines = []
            for variant_key, variant_data in sorted(variants.items()):
                cog = variant_data.get("cognizable")
                bail = variant_data.get("bailable")
                years = variant_data.get("max_years")
                has_multiple = variant_data.get("has_multiple_conditions")
                line = f"  - {variant_key}: cognizable={cog}, bailable={bail}, max_years={years}"
                if has_multiple:
                    conditions = variant_data.get("all_conditions", [])
                    extracted_facts = []
                    for cond in conditions:
                        preview = cond.get("raw_text_preview", "")

                        # PATTERN 1 (original, Section 303-style): a
                        # numeric rupee threshold with an optional
                        # return/restoration qualifier.
                        threshold_match = re.search(r'less than ([\d,]+) rupees', preview)
                        if threshold_match:
                            mentions_return = "return" in preview.lower() or "restoration" in preview.lower()
                            fact = f"if the value of the property is less than Rs. {threshold_match.group(1)}"
                            if mentions_return:
                                fact += " and the property is returned/restored"
                            fact += f", this becomes: cognizable={cond.get('cognizable')}, bailable={cond.get('bailable')}"
                            extracted_facts.append(fact)
                            continue

                        # PATTERN 2 (NEW, Section 109-style): no numeric
                        # threshold, but the condition itself carries a
                        # short, real, plain-language description (e.g.
                        # "If such act causes hurt to any person") --
                        # this is exactly what the "condition" field
                        # already stores for such entries. Use it
                        # directly rather than treating its absence from
                        # Pattern 1 as "nothing could be extracted".
                        condition_desc = cond.get("condition", "")
                        is_generic_label = condition_desc.strip().lower() in ("general", "")
                        if condition_desc and not is_generic_label:
                            # condition_desc can itself be a multi-line
                            # raw preview fragment (confirmed real case:
                            # 109(1)'s second condition's "condition"
                            # field is "If such act causes hurt to\n
                            # Imprisonment for life, or\nCognizable...\n
                            # C" -- truncated mid-word). Take only the
                            # first line, which reliably holds the real
                            # descriptive clause before the punishment/
                            # classification columns begin.
                            first_line = condition_desc.split("\n")[0].strip()
                            if first_line and first_line.lower() != "general":
                                fact = (
                                    f"in the specific situation described as \"{first_line}\", "
                                    f"this becomes: cognizable={cond.get('cognizable')}, "
                                    f"bailable={cond.get('bailable')}"
                                )
                                extracted_facts.append(fact)

                    if extracted_facts:
                        line += (
                            " -- NOTE: this section has multiple conditions, confirmed from the "
                            "source data: " + "; ".join(extracted_facts) + ". State these specific "
                            "conditions as known facts -- do not tell the user these details are "
                            "unavailable or that an exception exists which couldn't be captured, "
                            "since the conditions ARE available and listed here. Do not add any "
                            "OTHER condition beyond what is stated here."
                        )
                    else:
                        # Genuine fallback: multiple conditions exist,
                        # NEITHER extraction pattern found anything
                        # usable in raw_text_preview -- here, and only
                        # here, is uncertainty actually honest.
                        line += (
                            " -- NOTE: this section has MULTIPLE conditions; the above is the "
                            "general-case classification only, and a real exception exists that "
                            "this system could not cleanly extract. Tell the user a specific "
                            "exception exists and to confirm the exact threshold with a lawyer."
                        )
                variant_lines.append(line)
            block += "\n\n[Known classification for this section, from the verified compliance table]\n" + "\n".join(variant_lines)

        blocks.append(block)
    return "\n\n---\n\n".join(blocks)

def answer_question(question):
    """Main entry point for the chat interface. Returns a dict describing
    the outcome, always including a 'state' field so the UI layer can
    render each case distinctly and honestly, per this project's
    established "surface uncertainty, don't silently guess" principle
    throughout every other retrieval layer built this session.

        Possible states:
      'unrelated'          -- not a legal question, redirected politely
      'covered_elsewhere_in_tool' -- about bank freezing or cheque bounce,
                               which this chat feature's corpus doesn't
                               cover yet, but the wider tool genuinely
                               handles via document upload -- redirected
                               there, not told "not covered"
      'adjacent_uncovered'  -- real legal question, but outside what this
                               tool covers anywhere (BNS/BNSS chat scope
                               or the document-upload domains)
      'classifier_unavailable' -- couldn't even classify the question
      'no_match'           -- in scope, but nothing in the corpus cleared
                               the similarity threshold, AND no curated
                               statute override matched either
      'single_match'       -- one coherent, agreeing set of matches
      'conflicting_matches' -- multiple matches that disagree on a key
                               legal attribute (e.g. cognizability) --
                               never silently picks one
      'retrieval_unavailable' -- embeddings aren't set up (no API key,
                               no embeddings file, etc.)

    FIXED 2026-08-28: the conflicting_matches branch was previously
    nested INSIDE the no_match check's if-block (an indentation bug),
    making it unreachable -- since no_match returns immediately on its
    own condition, the nested conflicting_matches check could only ever
    fire if result["state"] was simultaneously "no_match" AND
    "conflicting_matches", which never happens. Real consequence: a
    genuine conflicting-matches result was silently falling through to
    the single_match handling below, mislabeling a conflict as a clean
    match. Fixed by making conflicting_matches a proper sibling
    elif, checked before the single_match fallthrough.

    ADDED 2026-08-28: a curated statute doctrine override check
    (statute_doctrine_map.py), covering known gaps where semantic
    search under-retrieves a specific high-stakes statute section
    (currently: BNSS 43(5), night-arrest-of-women safeguard, which
    scores ~0.343 against real "arrested at night" queries --
    indistinguishable from the confirmed-irrelevant ceiling ~0.339,
    per this project's own Aug 27 calibration data). This check runs
    BEFORE the normal semantic-search state handling, so it applies
    regardless of what score semantic search assigns -- it's a
    deliberate bypass for specific, known, verified gaps, not a
    replacement for semantic search generally. See
    statute_doctrine_map.py's module docstring for full reasoning and
    scope limits.
    """
    from semantic_retrieval import find_relevant_sections
    from statute_doctrine_map import get_statute_doctrine_override

    category, reasoning, redirect_domain = classify_scope(question)

    if category is None:
        return {"state": "classifier_unavailable"}

    if category == "unrelated":
        return {"state": "unrelated"}

    if category == "covered_elsewhere_in_tool":
        return {"state": "covered_elsewhere_in_tool", "reasoning": reasoning, "redirect_domain": redirect_domain}

    if category == "adjacent_uncovered":
        return {"state": "adjacent_uncovered", "reasoning": reasoning}

    # category == "in_scope" from here on

    # Curated statute override check -- runs BEFORE normal semantic
    # retrieval's state handling, so a known high-stakes gap (like
    # BNSS 43(5)) surfaces even if the embedding score alone wouldn't
    # clear SIMILARITY_THRESHOLD. This does NOT replace semantic
    # search -- both run, and both sets of results get combined below.
    statute_overrides = get_statute_doctrine_override(question)

    result = find_relevant_sections(question)

    if result["state"] == "unavailable":
        # Even if retrieval is unavailable, a curated override may
        # still apply -- don't discard it just because the general
        # embedding-based path is down.
        if statute_overrides:
            retrieved_text = format_retrieved_text_for_prompt(statute_overrides)
            response_text = generate_grounded_response(question, retrieved_text)
            return {
                "state": "single_match",
                "matches": statute_overrides,
                "response_text": response_text,
            }
        return {"state": "retrieval_unavailable"}

    if result["state"] == "no_match":
        # A curated override can still provide an answer even when
        # normal semantic search found nothing above threshold --
        # this is the exact scenario the override exists for.
        if statute_overrides:
            retrieved_text = format_retrieved_text_for_prompt(statute_overrides)
            response_text = generate_grounded_response(question, retrieved_text)
            return {
                "state": "single_match",
                "matches": statute_overrides,
                "response_text": response_text,
            }
        return {"state": "no_match"}

    if result["state"] == "conflicting_matches":
        all_matches = result["matches"] + result.get("judgment_matches", []) + statute_overrides
        retrieved_text = format_retrieved_text_for_prompt(all_matches)
        response_text = generate_grounded_response(question, retrieved_text, is_conflict=True)
        return {
            "state": "conflicting_matches",
            "matches": all_matches,
            "response_text": response_text,
        }

    # single_match -- combine statute matches with judgment matches
    # (confirmed real fix: previously judgment_matches were computed by
    # find_relevant_sections but never actually used here, so case law
    # like Arnesh Kumar never reached the response generator even when
    # it was the single highest-scoring result overall) AND any
    # curated statute overrides that matched alongside the normal
    # semantic results.
    all_matches = result["matches"] + result.get("judgment_matches", []) + statute_overrides
    retrieved_text = format_retrieved_text_for_prompt(all_matches)
    response_text = generate_grounded_response(question, retrieved_text)
    return {
        "state": "single_match",
        "matches": all_matches,
        "response_text": response_text,
    }